#include "stdafx_zoli.h"
#include "controlbase.h"
#include "syscontrol.h"
#include "dialog.h"
#include "graphiccontrol.h"
#include "buttons.h"

#include "designer.h"
#include "designeroptions.h"

//---------------------------------------------


namespace NLIBNS
{


    static Settings settings;

    Settings GetSettings()
    {
        return settings;
    }

    void UpdateSettings(const Settings &newsettings)
    {
        settings = newsettings;
    }

    void TfrmOptions::InitializeFormAndControls() /* Control initialization function generated by the designer. Modifications will be lost. */
    {
        /* Generated member initialization. Do not modify. */
        SetLeft(486);
        SetTop(457);
        SetText(L"Options");
        SetShowPosition(fspParentMonitorCenter);
        SetBorderStyle(fbsDialog);
        SetBorderButtons(fbbSystemMenu | fbbMinimizeBox);
        SetClientRect(Rect(0, 0, 584, 134));

        dlgFolder = new FolderDialog();

        Pages = new PageControl();
        Pages->SetBounds(Rect(2, 2, 583, 103));
        Pages->SetAnchors(caLeft | caTop | caRight | caBottom);
        Pages->SetTabOrder(0);
        Pages->SetParent(this);

        pDesigner = Pages->AddTabPage(L"Designer Settings");

        cbLoadLast = new Checkbox();
        cbLoadLast->SetBounds(Rect(18, 19, 274, 35));
        cbLoadLast->SetText(L"Load last open project on startup.");
        cbLoadLast->SetTabOrder(0);
        cbLoadLast->SetParent(pDesigner);

        cbOnTop = new Checkbox();
        cbOnTop->SetBounds(Rect(330, 19, 530, 35));
        cbOnTop->SetText(L"Keep designer windows on top.");
        cbOnTop->SetTabOrder(1);
        cbOnTop->SetParent(pDesigner);

        cbSavePos = new Checkbox();
        cbSavePos->SetBounds(Rect(18, 43, 274, 59));
        cbSavePos->SetText(L"Save designer window positions and sizes.");
        cbSavePos->SetTabOrder(2);
        cbSavePos->SetParent(pDesigner);

        pCode = Pages->AddTabPage(L"Code Formatting");

        Groupbox1 = new Groupbox();
        Groupbox1->SetBounds(Rect(306, 11, 554, 57));
        Groupbox1->SetText(L"Indentation");
        Groupbox1->SetParentBackground(true);
        Groupbox1->SetTabOrder(1);
        Groupbox1->SetParent(pCode);

        cbTabIndent = new Checkbox();
        cbTabIndent->SetBounds(Rect(8, 20, 120, 36));
        cbTabIndent->SetText(L"Use tab character.");
        cbTabIndent->SetTabOrder(0);
        cbTabIndent->SetParent(Groupbox1);

        edIndent = new Edit();
        edIndent->SetBounds(Rect(192, 19, 234, 36));
        edIndent->SetText(L"4");
        edIndent->SetTabOrder(1);
        edIndent->SetParent(Groupbox1);

        Label1 = new Label();
        Label1->SetBounds(Rect(128, 21, 187, 34));
        Label1->SetText(L"Indent size:");
        Label1->SetTransparent(true);
        Label1->SetParent(Groupbox1);

        cbPubTop = new Checkbox();
        cbPubTop->SetBounds(Rect(17, 30, 233, 47));
        cbPubTop->SetText(L"Print \"public:\" first in class definition.");
        cbPubTop->SetTabOrder(0);
        cbPubTop->SetParent(pCode);

        pPaths = Pages->AddTabPage(L"Library Paths");
        pPaths->SetBounds(Rect(4, 24, 577, 97));

        Label2 = new Label();
        Label2->SetBounds(Rect(10, 16, 74, 29));
        Label2->SetText(L"Library path:");
        Label2->SetTransparent(true);
        Label2->SetParent(pPaths);

        edLibPath = new Edit();
        edLibPath->SetBounds(Rect(90, 13, 525, 34));
        edLibPath->SetText(L".");
        edLibPath->SetAnchors(caLeft | caTop | caRight);
        edLibPath->SetTabOrder(0);
        edLibPath->SetParent(pPaths);

        btnLibPath = new Button();
        btnLibPath->SetBounds(Rect(533, 11, 562, 34));
        btnLibPath->SetText(L"...");
        btnLibPath->SetAnchors(caTop | caRight);
        btnLibPath->SetTabOrder(1);
        btnLibPath->SetParent(pPaths);

        Label3 = new Label();
        Label3->SetBounds(Rect(10, 48, 77, 61));
        Label3->SetText(L"Header path:");
        Label3->SetTransparent(true);
        Label3->SetParent(pPaths);

        edHeaderPath = new Edit();
        edHeaderPath->SetBounds(Rect(90, 46, 525, 67));
        edHeaderPath->SetText(L".");
        edHeaderPath->SetAnchors(caLeft | caTop | caRight);
        edHeaderPath->SetTabOrder(2);
        edHeaderPath->SetParent(pPaths);

        btnHeaderPath = new Button();
        btnHeaderPath->SetBounds(Rect(533, 43, 562, 66));
        btnHeaderPath->SetText(L"...");
        btnHeaderPath->SetAnchors(caTop | caRight);
        btnHeaderPath->SetTabOrder(3);
        btnHeaderPath->SetParent(pPaths);

        pEditing = Pages->AddTabPage(L"Control editing");

        Label4 = new Label();
        Label4->SetBounds(Rect(10, 32, 170, 45));
        Label4->SetText(L"Default access of new controls:");
        Label4->SetTransparent(true);
        Label4->SetParent(pEditing);

        cbCtrlAccess = new Combobox();
        cbCtrlAccess->SetBounds(Rect(186, 28, 266, 49));
        cbCtrlAccess->SetText(L"public");
        cbCtrlAccess->SetTabOrder(0);
        cbCtrlAccess->SetType(ctDropdownList);
        cbCtrlAccess->Items().Add(L"public");
        cbCtrlAccess->Items().Add(L"protected");
        cbCtrlAccess->Items().Add(L"private");
        cbCtrlAccess->SetItemIndex(0);
        cbCtrlAccess->SetParent(pEditing);

        btnOk = new Button();
        btnOk->SetBounds(Rect(406, 106, 486, 130));
        btnOk->SetText(L"Ok");
        btnOk->SetAnchors(caRight | caBottom);
        btnOk->SetTabOrder(1);
        btnOk->SetParent(this);

        btnCancel = new Button();
        btnCancel->SetBounds(Rect(494, 106, 574, 130));
        btnCancel->SetText(L"Cancel");
        btnCancel->SetAnchors(caRight | caBottom);
        btnCancel->SetTabOrder(2);
        btnCancel->SetParent(this);

        SetActiveControl(cbLoadLast);
        Pages->SetActivePage(pDesigner);
        cbLoadLast->OnCheck = CreateEvent(this, &TfrmOptions::cbloadlastcheck);
        cbOnTop->OnCheck = CreateEvent(this, &TfrmOptions::cbontopcheck);
        cbSavePos->OnCheck = CreateEvent(this, &TfrmOptions::cbsaveposcheck);
        cbTabIndent->OnCheck = CreateEvent(this, &TfrmOptions::cbtabindentcheck);
        edIndent->OnKeyDown = CreateEvent(this, &TfrmOptions::edindentkeydown);
        edIndent->OnKeyPress = CreateEvent(this, &TfrmOptions::edindentkeypress);
        edIndent->OnTextChanged = CreateEvent(this, &TfrmOptions::edindenttextchanged);
        cbPubTop->OnCheck = CreateEvent(this, &TfrmOptions::cbpubtopcheck);
        btnLibPath->OnClick = CreateEvent(this, &TfrmOptions::btnlibpathclick);
        btnHeaderPath->OnClick = CreateEvent(this, &TfrmOptions::btnheaderpathclick);
        btnOk->OnClick = CreateEvent(this, &TfrmOptions::btnokclick);
        btnCancel->OnClick = CreateEvent(this, &TfrmOptions::btncancelclick);
    }

    TfrmOptions *frmOptions;

    TfrmOptions::TfrmOptions()
    {
	    InitializeFormAndControls();

    }

    TfrmOptions::~TfrmOptions() {}

    void TfrmOptions::Destroy()
    {
        /* Controls are not valid in the destructor. Use this function for finalization. */
        /* ... Your code here ... */

        Form::Destroy();
    }

    ModalResults TfrmOptions::ShowModal()
    {
        cbLoadLast->SetChecked(settings.designer_loadlast);
        cbOnTop->SetChecked(settings.designer_ontop);
        cbSavePos->SetChecked(settings.designer_savepos);
        cbPubTop->SetChecked(settings.code_publictop);
        cbTabIndent->SetChecked(settings.code_tabindent);
        edIndent->SetText(IntToStr(settings.code_indentsize));
        edIndent->SetEnabled(!cbTabIndent->Checked());
        edLibPath->SetText(settings.paths_library);
        edHeaderPath->SetText(settings.paths_headers);
        cbCtrlAccess->SetItemIndex(settings.control_access);

        ModalResults mr = Form::ShowModal();
        if (mr == mrOk)
        {
            settings.designer_loadlast = cbLoadLast->Checked();
            settings.designer_ontop = cbOnTop->Checked();
            settings.designer_savepos = cbSavePos->Checked();
            settings.code_publictop = cbPubTop->Checked();
            settings.code_tabindent = cbTabIndent->Checked();
            int indent;
            if (StrToInt(edIndent->Text(), indent))
                settings.code_indentsize = indent;
            settings.paths_library = edLibPath->Text();
            settings.paths_headers = edHeaderPath->Text();
            settings.control_access = (AccessLevels)cbCtrlAccess->ItemIndex();
        }
        return mr;
    }

    void TfrmOptions::cbloadlastcheck(void *sender, CheckboxCheckParameters param)
    {
        ;
    }

    void TfrmOptions::cbontopcheck(void *sender, CheckboxCheckParameters param)
    {
        ;
    }

    void TfrmOptions::cbsaveposcheck(void *sender, CheckboxCheckParameters param)
    {
        ;
    }

    void TfrmOptions::cbtabindentcheck(void *sender, CheckboxCheckParameters param)
    {
        edIndent->SetEnabled(param.newstate != csChecked);
    }

    void TfrmOptions::edindentkeydown(void *sender, KeyParameters param)
    {
        ;
    }

    void TfrmOptions::edindentkeypress(void *sender, KeyPressParameters param)
    {
        ;
    }

    void TfrmOptions::edindenttextchanged(void *sender, EventParameters param)
    {
        ;
    }

    void TfrmOptions::cbpubtopcheck(void *sender, CheckboxCheckParameters param)
    {
        ;
    }

    void TfrmOptions::btnlibpathclick(void *sender, EventParameters param)
    {
        if (dlgFolder->Show(this))
            edLibPath->SetText(dlgFolder->Folder());
    }

    void TfrmOptions::btnheaderpathclick(void *sender, EventParameters param)
    {
        if (dlgFolder->Show(this))
            edHeaderPath->SetText(dlgFolder->Folder());
    }

    void TfrmOptions::btnokclick(void *sender, EventParameters param)
    {
        SetModalResult(mrOk);
    }

    void TfrmOptions::btncancelclick(void *sender, EventParameters param)
    {
        SetModalResult(mrCancel);
    }


}
/* End of NLIBNS */
