#include "stdafx_zoli.h"
#include "controlbase.h"
#include "syscontrol.h"
#include "dialog.h"
#include "graphiccontrol.h"
#include "buttons.h"
#include "resource.h"

#include "designer.h"
#include "designerdialogs.h"
#include "projectsettings.h"
#include "designerform.h"

//---------------------------------------------


namespace NLIBNS
{


TfrmProjSettings *frmProjSettings;
const wchar_t formcreatedstr[] = L"(created)";

void TfrmProjSettings::InitializeFormAndControls() /* Control initialization function generated by the designer. Modifications will be lost. */
{
    /* Generated member initialization. Do not modify. */
    SetLeft(598);
    SetTop(559);
    SetText(L"Project Settings");
    SetShowPosition(fspParentMonitorCenter);
    SetBorderStyle(fbsDialog);
    SetBorderButtons(fbbSystemMenu | fbbMinimizeBox);
    SetClientRect(Rect(0, 0, 593, 187));

    dlgFolder = new FolderDialog();

    btnOk = new Button();
    btnOk->SetBounds(Rect(434, 160, 509, 183));
    btnOk->SetText(L"Ok");
    btnOk->SetAnchors(caRight | caBottom);
    btnOk->SetTabOrder(0);
    btnOk->SetParent(this);

    btnCancel = new Button();
    btnCancel->SetBounds(Rect(514, 160, 589, 183));
    btnCancel->SetText(L"Cancel");
    btnCancel->SetAnchors(caRight | caBottom);
    btnCancel->SetTabOrder(1);
    btnCancel->SetCancel(true);
    btnCancel->SetParent(this);

    PageControl1 = new PageControl();
    PageControl1->SetBounds(Rect(2, 1, 591, 155));
    PageControl1->SetText(L"PageControl1");
    PageControl1->SetAnchors(caLeft | caTop | caRight | caBottom);
    PageControl1->SetTabOrder(2);
    PageControl1->SetParent(this);

    TabPage1 = PageControl1->AddTabPage(L"Properties");
    TabPage1->SetBounds(Rect(4, 22, 585, 150));

    edProjName = new Edit();
    edProjName->SetBounds(Rect(112, 15, 257, 36));
    edProjName->SetTabOrder(0);
    edProjName->SetParent(TabPage1);

    Label1 = new Label();
    Label1->SetBounds(Rect(16, 18, 85, 31));
    Label1->SetText(L"&Project name:");
    Label1->SetTransparent(true);
    Label1->SetParent(TabPage1);

    pbAppIcon = new Paintbox();
    pbAppIcon->SetBounds(Rect(112, 47, 176, 111));
    pbAppIcon->SetTabOrder(1);
    pbAppIcon->SetParent(TabPage1);

    Label7 = new Label();
    Label7->SetBounds(Rect(16, 51, 103, 64));
    Label7->SetText(L"Application icon:");
    Label7->SetTransparent(true);
    Label7->SetParent(TabPage1);

    btnChangeIcon = new Button();
    btnChangeIcon->SetBounds(Rect(181, 46, 256, 69));
    btnChangeIcon->SetText(L"&Change...");
    btnChangeIcon->SetTabOrder(2);
    btnChangeIcon->SetParent(TabPage1);

    Label8 = new Label();
    Label8->SetBounds(Rect(296, 10, 330, 23));
    Label8->SetText(L"Forms:");
    Label8->SetTransparent(true);
    Label8->SetParent(TabPage1);

    lbForms = new Listbox();
    lbForms->SetBounds(Rect(338, 9, 506, 117));
    lbForms->SetText(L"lbForms");
    lbForms->SetTabOrder(3);
    lbForms->SetParent(TabPage1);

    btnFormUp = new FlatButton();
    btnFormUp->SetBounds(Rect(511, 9, 533, 32));
    btnFormUp->SetTabOrder(4);
    btnFormUp->SetImagePosition(bipCenter);
    btnFormUp->SetParent(TabPage1);

    btnFormDown = new FlatButton();
    btnFormDown->SetBounds(Rect(511, 33, 533, 56));
    btnFormDown->SetTabOrder(5);
    btnFormDown->SetImagePosition(bipCenter);
    btnFormDown->SetParent(TabPage1);

    btnFormDel = new FlatButton();
    btnFormDel->SetBounds(Rect(511, 94, 533, 117));
    btnFormDel->SetTabOrder(6);
    btnFormDel->SetImagePosition(bipCenter);
    btnFormDel->SetParent(TabPage1);

    cbFormCreate = new Checkbox();
    cbFormCreate->SetBounds(Rect(511, 62, 568, 78));
    cbFormCreate->SetText(L"Created");
    cbFormCreate->SetTabOrder(7);
    cbFormCreate->SetParent(TabPage1);

    TabPage2 = PageControl1->AddTabPage(L"Files");
    TabPage2->SetBounds(Rect(4, 22, 585, 150));

    edPath = new Edit();
    edPath->SetBounds(Rect(8, 24, 537, 45));
    edPath->SetAnchors(caLeft | caTop | caRight);
    edPath->SetTabOrder(0);
    edPath->SetParent(TabPage2);

    Label4 = new Label();
    Label4->SetBounds(Rect(6, 5, 97, 18));
    Label4->SetText(L"&Source file folder:");
    Label4->SetTransparent(true);
    Label4->SetParent(TabPage2);

    btnPath = new Button();
    btnPath->SetBounds(Rect(541, 22, 574, 45));
    btnPath->SetText(L"...");
    btnPath->SetAnchors(caTop | caRight);
    btnPath->SetTabOrder(1);
    btnPath->SetParent(TabPage2);

    edRes = new Edit();
    edRes->SetBounds(Rect(8, 69, 537, 90));
    edRes->SetAnchors(caLeft | caTop | caRight);
    edRes->SetTabOrder(2);
    edRes->SetParent(TabPage2);

    Label6 = new Label();
    Label6->SetBounds(Rect(8, 50, 128, 63));
    Label6->SetText(L"&Resource export folder:");
    Label6->SetTransparent(true);
    Label6->SetParent(TabPage2);

    btnRes = new Button();
    btnRes->SetTag(1);
    btnRes->SetBounds(Rect(541, 67, 574, 90));
    btnRes->SetText(L"...");
    btnRes->SetAnchors(caTop | caRight);
    btnRes->SetTabOrder(3);
    btnRes->SetParent(TabPage2);

    Label5 = new Label();
    Label5->SetBounds(Rect(8, 99, 155, 112));
    Label5->SetText(L"C++/ Header file &extensions:");
    Label5->SetTransparent(true);
    Label5->SetParent(TabPage2);

    edSrcExt = new Edit();
    edSrcExt->SetBounds(Rect(163, 96, 227, 117));
    edSrcExt->SetText(L"cpp");
    edSrcExt->SetTabOrder(4);
    edSrcExt->SetParent(TabPage2);

    edHeadExt = new Edit();
    edHeadExt->SetBounds(Rect(235, 96, 299, 117));
    edHeadExt->SetText(L"h");
    edHeadExt->SetTabOrder(5);
    edHeadExt->SetParent(TabPage2);

    btnOk->OnClick = CreateEvent(this, &TfrmProjSettings::btnOkClick);
    btnCancel->OnClick = CreateEvent(this, &TfrmProjSettings::btnCancelClick);
    PageControl1->SetActivePage(TabPage1);
    Label1->SetAccessControl(edProjName);
    pbAppIcon->OnPaint = CreateEvent(this, &TfrmProjSettings::pbAppIconPaint);
    btnChangeIcon->OnClick = CreateEvent(this, &TfrmProjSettings::btnChangeIconClick);
    lbForms->OnChanged = CreateEvent(this, &TfrmProjSettings::lbFormsChanged);
    btnFormUp->OnClick = CreateEvent(this, &TfrmProjSettings::btnFormUpClick);
    btnFormDown->OnClick = CreateEvent(this, &TfrmProjSettings::btnFormDownClick);
    btnFormDel->OnClick = CreateEvent(this, &TfrmProjSettings::btnFormDelClick);
    cbFormCreate->OnClick = CreateEvent(this, &TfrmProjSettings::cbFormCreateClick);
    Label4->SetAccessControl(edPath);
    btnPath->OnClick = CreateEvent(this, &TfrmProjSettings::btnPathClick);
    Label6->SetAccessControl(edRes);
    btnRes->OnClick = CreateEvent(this, &TfrmProjSettings::btnPathClick);
    Label5->SetAccessControl(edSrcExt);
}

TfrmProjSettings::TfrmProjSettings() : icon(NULL), formschanged(false), formdeleted(false)
{
    InitializeFormAndControls();
    btnFormUp->Image()->SetBitmap(new Bitmap(NULL, MAKEINTRESOURCE(IDI_UPBUTTON)));
    btnFormDown->Image()->SetBitmap(new Bitmap(NULL, MAKEINTRESOURCE(IDI_DOWNBUTTON)));
    btnFormDel->Image()->SetBitmap(new Bitmap(NULL, MAKEINTRESOURCE(IDI_DELBUTTON)));
}

TfrmProjSettings::~TfrmProjSettings()
{
    delete icon;
}

void TfrmProjSettings::Destroy()
{
    /* Controls are not valid in the destructor. Use this function for finalization. */
    /* ... Your code here ... */

    Form::Destroy();
}

ModalResults TfrmProjSettings::ShowModal()
{
    edProjName->SetText(project->Name()); 
    edPath->SetText(project->SourcePath());
    edRes->SetText(project->ResourcePath());
    edSrcExt->SetText(project->CppExt());
    edHeadExt->SetText(project->HeaderExt());
    icondata = *project->AppIcon();
    GenerateIcon();

    lbForms->BeginUpdate();
    int cnt = project->FormCount();
    for (int ix = 0; ix < cnt; ++ix)
    {
        bool autocreate = project->Forms(ix)->AutoCreate();
        if (autocreate)
            ++frmcreated;
        lbForms->Items().Add(project->Forms(ix)->Name() + (autocreate ? std::wstring(L" ") + formcreatedstr : std::wstring()), (void*)ix);
    }
    lbForms->EndUpdate();
    UpdateFormButtons();

    ModalResults mr = Form::ShowModal();
    if (mr == mrOk)
    {
        project->SetName(edProjName->Text()); 
        project->SetSourcePath(edPath->Text());
        project->SetResourcePath(edRes->Text());
        project->SetCppExt(edSrcExt->Text());
        project->SetHeaderExt(edHeadExt->Text());
        project->SetAppIcon(std::move(icondata));

        if (formschanged)
        {
            std::vector<std::wstring> forms;
            cnt = lbForms->Count();
            for (int ix = 0; ix < cnt; ++ix)
            {
                size_t cpos = lbForms->ItemText(ix).find(formcreatedstr);
                DesignFormBase *form = project->Forms((int)lbForms->ItemData(ix));
                form->SetAutoCreate(cpos != std::wstring::npos);
                if (cpos == std::wstring::npos)
                    forms.push_back(lbForms->ItemText(ix));
                else
                    forms.push_back(lbForms->ItemText(ix).substr(0, cpos - 1));
            }
            project->ReorderForms(forms);
        }
    }

    return mr;
}

void TfrmProjSettings::UpdateFormButtons()
{
    int ix = lbForms->ItemIndex();
    int cnt = lbForms->Count();
    btnFormUp->SetEnabled(ix > 0);
    btnFormDown->SetEnabled(ix >= 0 && ix < cnt - 1);
    btnFormDel->SetEnabled(ix >= 0 && cnt > 1);
    cbFormCreate->SetEnabled(ix >= 0);
    cbFormCreate->SetChecked(ix >= 0 && lbForms->ItemText(ix).find(formcreatedstr) != std::wstring::npos);
}

void TfrmProjSettings::GenerateIcon()
{
    delete icon;
    icon = NULL;

    if (!icondata.filedata)
        return;

    std::vector<IconEntry> entries;
    HDC dc = GetDC(0);
    try
    {
        FillIconEntryVector(icondata.filedata, icondata.filesize, entries, false);
        int entry = FindNearestIconEntry(entries, GetSystemMetrics(SM_CXICON), GetSystemMetrics(SM_CYICON), GetDeviceCaps(dc, BITSPIXEL), false);
        if (entry < 0)
            throw L"No icon entry in icon file.";
        HICON hicon = CreateIconFromResourceEx((byte*)icondata.filedata + entries[entry].icondirentry.dataoffset, entries[entry].icondirentry.datasize, TRUE,  0x00030000, GetSystemMetrics(SM_CXICON), GetSystemMetrics(SM_CYICON), 0);
        if (!hicon)
            throw L"Couldn't load icon.";
        Icon tmp(hicon);
        icon = new Bitmap();
        if (icon)
            tmp.ToBitmap(*icon);
    }
    catch(...)
    {
        if (icon)
            delete icon;
        icon = NULL;
    }
    ReleaseDC(0, dc);
}

void TfrmProjSettings::btnPathClick(void *sender, EventParameters param)
{
    tagtype tag = ((Button*)sender)->Tag();
    std::wstring root = GetFilePath(project->Path());
    std::wstring path = (tag == 0 ? edPath->Text() : edRes->Text()) + L"\\";
    if (path.empty() || (path.length() < 2 || ((path.length() <= 2 || path[0] != L'\\' || path[1] != L'\\') && (((path[0] < L'a' || path[0] > 'z') && (path[0] < L'A' || path[0] > 'Z')) || path[1] != L':')) ) )
        path = AppendToPath(root, path);
    else
        path = ShortenRelativePath(path);

    dlgFolder->SetInitialFolder(path);
    if (dlgFolder->Show(this))
    {
        path = dlgFolder->Folder() + L"\\";
        if (GenToLower(path).find(GenToLower(root)) == 0)
            path.replace(0, root.length(), L".\\");
        switch (tag)
        {
        case 0:
            edPath->SetText(ShortenRelativePath(path + L"\\"));
            break;
        case 1:
            edRes->SetText(ShortenRelativePath(path + L"\\"));
            break;
        }
    }
}

void TfrmProjSettings::btnOkClick(void *sender, EventParameters param)
{
    SetModalResult(mrOk);
}

void TfrmProjSettings::btnCancelClick(void *sender, EventParameters param)
{
    SetModalResult(mrCancel);
}

void TfrmProjSettings::btnChangeIconClick(void *sender, EventParameters param)
{
    IconSelectorDialog dialog;
    try
    {
        if (dialog.Show(this, icondata))
        {
            icondata = std::move(dialog.GetIcon());
            GenerateIcon();
            pbAppIcon->Invalidate();
        }
    }
    catch(...)
    {
        ;
    }
}

void TfrmProjSettings::pbAppIconPaint(void *sender, PaintParameters param)
{
    Canvas *c = param.canvas;
    c->SelectStockBrush(sbWindow);
    c->FillRect(param.updaterect);
    if (!icon)
        return;

    Rect cr = pbAppIcon->ClientRect();
    double div = min(1, min(48.0 / icon->Width(), 48.0 / icon->Height()));
    int draww = div * icon->Width();
    int drawh = div * icon->Height();
    c->Draw(icon, (cr.Width() - draww) / 2, (cr.Height() - drawh) / 2, draww, drawh, 0, 0, icon->Width(), icon->Height());
}

void TfrmProjSettings::btnFormDownClick(void *sender, EventParameters param)
{
    int ix = lbForms->ItemIndex();
    if (ix < 0 || ix == lbForms->Count() - 1)
        return;
    lbForms->SwapItems(ix, ix + 1);
    lbForms->SetItemIndex(ix + 1);
    formschanged = true;
    UpdateFormButtons();
}

void TfrmProjSettings::btnFormUpClick(void *sender, EventParameters param)
{
    int ix = lbForms->ItemIndex();
    if (ix < 1)
        return;
    lbForms->SwapItems(ix, ix - 1);
    lbForms->SetItemIndex(ix - 1);
    formschanged = true;
    UpdateFormButtons();
}

void TfrmProjSettings::cbFormCreateClick(void *sender, EventParameters param)
{
    int ix = lbForms->ItemIndex();
    if (ix < 0)
        return;
    if (cbFormCreate->Checked() && lbForms->ItemText(ix).find(formcreatedstr) == std::wstring::npos)
        lbForms->SetItemText(ix, lbForms->ItemText(ix) + L" " + formcreatedstr);
    else if (!cbFormCreate->Checked() && lbForms->ItemText(ix).find(formcreatedstr) != std::wstring::npos)
        lbForms->SetItemText(ix, lbForms->ItemText(ix).substr(0, lbForms->ItemText(ix).find(formcreatedstr) - 1));
    lbForms->SetItemIndex(ix);
    UpdateFormButtons();
}


void TfrmProjSettings::lbFormsChanged(void *sender, EventParameters param)
{
    UpdateFormButtons();
}

void TfrmProjSettings::btnFormDelClick(void *sender, EventParameters param)
{
    int ix = lbForms->ItemIndex();
    if (ix < 0)
        return;

    if (ShowMessageBox(L"Would you like to delete the selected form? This change cannot be undone.", L"Query", mbYesNo) == mrNo)
        return;

    DesignFormBase *form = project->Forms((int)lbForms->ItemData(ix));

    if (!form->UnitName().empty())
    {
        std::wstring root = project->ResolvedSourcePath();
        std::wstring fname = AppendToPath(root, form->UnitName());
        std::wstring fhname = fname + L"." + project->HeaderExt();
        std::wstring fsname = fname + L"." + project->CppExt();
        bool fh = false, fs = false;
        if (((ValidFileName(fhname, true) && (fh = FileExists(fhname))) || (ValidFileName(fsname, true) && (fs = FileExists(fsname)))) &&
            ShowMessageBox(L"Delete the files associated with the form from the disk? This change cannot be undone.", L"Query", mbYesNo) == mrYes)
        {
            bool success = true;
            if (fh)
                success &= DeleteFile(fhname.c_str()) != 0;
            if (fs)
                success &= DeleteFile(fsname.c_str()) != 0;
            if (!success && ShowMessageBox(L"Couldn't delete one or both files from the disk. Would you still like to exclude the form from the project?", L"Error", mbYesNo) != mrYes)
                return;
        }
    }

    int cnt = lbForms->Count();
    for (int iy = 0; iy < cnt; ++iy)
    {
        if (iy == ix)
            continue;
        if ((int)lbForms->ItemData(iy) > ix)
            lbForms->SetItemData(iy, (void*)((int)lbForms->ItemData(iy) - 1));
    }

    project->FormDelete((int)lbForms->ItemData(ix));
    lbForms->DeleteItem(ix);
    formdeleted = true;
    UpdateFormButtons();
}

bool TfrmProjSettings::FormsChanged()
{
    return formdeleted || (formschanged && ModalResult() == mrOk);
}


}
/* End of NLIBNS */
