#include "Stdafx_zoli.h"

using namespace nlib;
#include "about.h"

TfrmAbout *frmAbout;

void TfrmAbout::InitializeFormAndControls() /* Control initialization function generated by the designer. Modifications will be lost. */
{
	/* Generated member initialization. Do not modify. */
	SetLeft(524);
	SetTop(67);
	SetText(L"About LittlaCalc++");
	GetFont().SetFamily(L"Tahoma");
	SetWantedKeyTypes(nlib::wkArrows | nlib::wkTab | nlib::wkEnter | nlib::wkEscape | nlib::wkOthers);
	SetShowPosition(nlib::fspActiveMonitorCenter);
	SetBorderStyle(nlib::fbsDialog);
	SetKeyPreview(true);
	SetClientRect(nlib::Rect(0, 0, 274, 222));

	Label1 = new nlib::Label();
	Label1->SetBounds(nlib::Rect(86, 15, 189, 34));
	Label1->SetText(L"FalconCalc");
	Label1->GetFont().SetFamily(L"Tahoma");
	Label1->GetFont().SetSize(12);
	Label1->GetFont().SetBold(true);
	Label1->SetParentFont(false);
	Label1->SetParent(this);

	Label2 = new nlib::Label();
	Label2->SetBounds(nlib::Rect(44, 47, 245, 61));
	Label2->SetText(L"A handy little calculator for everyone");
	Label2->SetParent(this);

	Label3 = new nlib::Label();
	Label3->SetBounds(nlib::Rect(39, 71, 252, 85));
	Label3->SetText(L"(but especially useful for programmers)");
	Label3->SetParent(this);

	Label4 = new nlib::Label();
	Label4->SetBounds(nlib::Rect(50, 95, 242, 109));
	Label4->SetText(L"Based on the 'FalconCalc Engine',");
	Label4->SetParent(this);

	Label5 = new nlib::Label();
	Label5->SetBounds(nlib::Rect(54, 119, 233, 133));
	Label5->SetText(L"a cross platform arithmetic library");
	Label5->SetParent(this);

	Label6 = new nlib::Label();
	Label6->SetBounds(nlib::Rect(108, 143, 169, 157));
	Label6->SetText(L"Copyright");
	Label6->GetFont().SetFamily(L"Tahoma");
	Label6->GetFont().SetBold(true);
	Label6->SetParentFont(false);
	Label6->SetParent(this);

	Label7 = new nlib::Label();
	Label7->SetBounds(nlib::Rect(85, 167, 200, 181));
	Label7->SetText(L"A. Sólyom - 2012. ");
	Label7->GetFont().SetFamily(L"Tahoma");
	Label7->GetFont().SetBold(true);
	Label7->SetParentFont(false);
	Label7->SetParent(this);

	Label8 = new nlib::Label();
	Label8->SetBounds(nlib::Rect(46, 191, 242, 205));
	Label8->SetText(L"This program is in the public domain");
	Label8->SetParent(this);


	OnKeyDown = CreateEvent(this, &TfrmAbout::frmAboutKeyDown);
	OnClick = CreateEvent(this, &TfrmAbout::frmAboutClick);
}

void TfrmAbout::Destroy()
{
	/* Controls are valid here, but not in the destructor. */
	/* ... Your code here ... */

	Form::Destroy();
}

TfrmAbout::TfrmAbout()
{
	InitializeFormAndControls();
}

TfrmAbout::~TfrmAbout()
{
	/* Don't 'delete' the form. Call Destroy() instead which has access to the protected destructor. */
}

void TfrmAbout::frmAboutClick(void *sender, nlib::EventParameters param)
{
    Close();
}

void TfrmAbout::frmAboutKeyDown(void *sender, nlib::KeyParameters param)
{
    Close();
}


