#pragma once
#ifndef _ENGINEERRORS_H
	#define _ENGINEERRORS_H

#ifdef QTSA_PROJECT
    #include <QString>
#endif

enum EngineErrorCodes {
    EEC_NO_ERROR = 0,
    EEC_VARIABLE_DEFINITION_MISSING,
    EEC_UNKNOWN_FUNCTION_IN_EXPRESSION,
    EEC_SYNTAX_ERROR,
    EEC_STACK_ERROR,
    EEC_OVERFLOW_ERROR,
    EEC_DOMAIN_ERROR,
    EEC_MISSING_BRACE,
    EEC_LARGE_FOR64,
    EEC_RECURSIVE_FUNCTIONS_ARE_NOT_ALLOWED,
    EEC_NO_FUNCTION_ARGUMENT,
    EEC_MISSING_BINARY_NUMBER,
    EEC_MISMATCHED_PARENTHESIS,
    EEC_INVALID_FUNCTION_DEFINITION,
    EEC_INVALID_CHARACTER_IN_FUNCTION_DEFINITION,
    EEC_ILLEGAL_OPERATOR_AT_LINE_END,
    EEC_ILLEGAL_OCTAL_NUMBER,
    EEC_ILLEGAL_NUMBER_No2,
    EEC_ILLEGAL_NUMBER_No1,
    EEC_ILLEGAL_HEXADECIMAL_NUMBER,
    EEC_ILLEGAL_CHARACTER_NUMBER,
    EEC_ILLEGAL_BINARY_NUMBER,
    EEC_ILLEGAL_AT_LINE_END,
    EEC_FUNCTION_MISSING_OPENING_BRACE,
    EEC_FUNCTION_DEFINITION_MISSING_RIGHT_BRACE,
    EEC_EXPRESSION_ERROR,
    EEC_SEPARATOR_DECPOINT_BRACE_MISMATCH,
    EEC_DIVISON_BY_0,
    EEC_CLOSING_QUOTE_NOT_FOUND,
    EEC_BUILTIN_VARIABLES_CANNOT_BE_REDEFINED,
    EEC_BUILTIN_FUNCTIONS_CANNOT_BE_REDEFINED,
    EEC_UNKNOWN_ERROR,                                 // no error text for this code!
    EEC_TOP                                            // stop code, all definitions are below this
};

#ifdef QTSA_PROJECT
    QString EngineErrorString(EngineErrorCodes eec);
#endif



#endif