#include "stdafx_zoli.h"
#include "stdafx_lc.h"
#include "frmLocale.h"
#include <locale>
#include <codecvt>

TfrmLocale *frmLocale;

void TfrmLocale::InitializeFormAndControls() /* Control initialization function generated by the designer. Modifications will be lost. */
{
	/* Generated member initialization. Do not modify. */
	SetLeft(597);
	SetTop(607);
	SetText(L"FalconCalc Locale");
	SetWantedKeyTypes(nlib::wkArrows | nlib::wkTab | nlib::wkEnter | nlib::wkEscape | nlib::wkOthers);
	SetClientRect(nlib::Rect(0, 0, 434, 223));
	SetBorderStyle(nlib::fbsDialog);
	SetBorderButtons(nlib::fbbSystemMenu);

	btnSave = new nlib::Button();
	btnSave->SetBounds(nlib::Rect(346, 190, 421, 213));
	btnSave->SetText(L"&Save");
	btnSave->SetEnabled(false);
	btnSave->SetAnchors(nlib::caRight | nlib::caBottom);
	btnSave->SetTabOrder(2);
	btnSave->SetParent(this);

	btnCancel = new nlib::Button();
	btnCancel->SetBounds(nlib::Rect(346, 160, 421, 183));
	btnCancel->SetText(L"&Cancel");
	btnCancel->SetAnchors(nlib::caRight | nlib::caBottom);
	btnCancel->SetTabOrder(1);
	btnCancel->SetCancel(true);
	btnCancel->SetParent(this);

	lblText = new nlib::Label();
	lblText->SetBounds(nlib::Rect(14, 159, 138, 164));
	lblText->SetAnchors(nlib::caLeft | nlib::caTop | nlib::caRight | nlib::caBottom);
	lblText->SetText(L"Name of current locale:");
	lblText->SetParent(this);

	lblInput = new nlib::Label();
	lblInput->SetBounds(nlib::Rect(14, 177, 122, 188));
	lblInput->SetText(L"Name of new locale:");
	lblInput->SetParent(this);

	lblOldLocale = new nlib::Label();
	lblOldLocale->SetBounds(nlib::Rect(153, 159, 161, 164));
	lblOldLocale->SetText(L"C");
	lblOldLocale->SetParent(this);

	edtLocale = new nlib::Edit();
	edtLocale->SetBounds(nlib::Rect(145, 176, 225, 195));
	edtLocale->SetText(L"C");
	edtLocale->SetTabOrder(0);
	edtLocale->SetParent(this);

	Panel1 = new nlib::Panel();
	Panel1->SetBounds(nlib::Rect(5, 7, 429, 142));	// 424 x 135
	Panel1->SetAnchors(nlib::caLeft | nlib::caTop | nlib::caRight);
	Panel1->SetTabOrder(3);
	Panel1->SetInnerBorderStyle(nlib::pbsRaisedSunken);
	Panel1->SetParent(this);

	Label1 = new nlib::Label();
	Label1->SetText(L"The locale determines the character used for a decimal point, the ordering of the characters"
		             " and the correspondance bewtween upper and lowercase letters. Variable and function names may"
					 " contain accented or special letters in your locale that are not present in other locales and vice-versa.");
	Label1->SetBounds(nlib::Rect(14, 13, 406, 73));	// 392 x 60
	Label1->SetAnchors(nlib::caLeft | nlib::caTop | nlib::caRight | nlib::caBottom);
	Label1->SetWordWrap(true);
	Label1->SetParent(Panel1);

	Label2 = new nlib::Label();
	Label2->SetText(L"Locale names usually consist of two lowercase and two uppercase letters separated"
					 " by an underline character. Examples: en_US and en_GB are both English locale names."
					 " The 'C' locale roughly corresponds to 'en_US'.");
	Label2->SetBounds(nlib::Rect(14, 77, 406, 122));	// 392 x 45
	Label2->SetAnchors(nlib::caLeft | nlib::caTop | nlib::caRight | nlib::caBottom);
	Label2->SetWordWrap(true);
	Label2->SetParent(Panel1);

	btnSave->OnClick = CreateEvent(this, &TfrmLocale::btnSaveClick);
	btnCancel->OnClick = CreateEvent(this, &TfrmLocale::btnCancelClick);
	edtLocale->OnKeyPress = CreateEvent(this, &TfrmLocale::edtLocaleKeypress);
}

TfrmLocale::TfrmLocale()
{
	InitializeFormAndControls(); /* Control initializations. Do not remove. */
	std::locale loc = std::cout.getloc();

	std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> converter;
	_wsLocName = converter.from_bytes(loc.name());
	lblOldLocale->SetText(_wsLocName);
	edtLocale->SetText	 (_wsLocName);
}

TfrmLocale::~TfrmLocale()
{
	/* Don't 'delete' the form. Call Destroy() instead which has access to the protected destructor. */
}

void TfrmLocale::Destroy()
{
	/* Controls are valid here, but not in the destructor. */
	/* ... Your code here ... */

	Form::Destroy();
}

std::wstring TfrmLocale::LocaleName() const
{
	return _wsLocName;
}

void TfrmLocale::btnSaveClick(void *sender, nlib::EventParameters param)
{
	_wsLocName = edtLocale->Text();
	SetModalResult(nlib::mrOk);
}

void TfrmLocale::btnCancelClick(void *sender, nlib::EventParameters param)
{
	SetModalResult(nlib::mrCancel);
}

void TfrmLocale::edtLocaleKeypress(void* sender, nlib::KeyPressParameters param)
{
	std::wstring ws = edtLocale->Text();
	btnSave->SetEnabled(ws != _wsLocName);
	// DEBUG
	nlib::Label* pl = Label1;
#ifdef _DEBUG
	wchar_t buf[2048];
	std::swprintf(buf, 2048, L"Label1:(%d, %d, %d, %d) (%d x %d)", pl->Left(), pl->Top(), pl->Right(), pl->Bottom(), pl->Width(), pl->Height());
	OutputDebugString(buf);
#endif
}

