#include "stdafx_zoli.h"
#include "stdafx_lc.h"
#include "frmLocale.h"
#include <locale>
#include <codecvt>
#include "translations.h"

TfrmLocale *frmLocale;

void TfrmLocale::InitializeFormAndControls() /* Control initialization function generated by the designer. Modifications will be lost. */
{

#define MY_RECT(l,t,w,h)	nlib::Rect((l), (t),(l)+(w), (t)+(h))
	
	SetLeft(597);											 // 340 x 446
	SetTop(607);
	SetText(lt.GetTranslationFor(FCT_LOCALETITLE));
	SetWantedKeyTypes(nlib::wkArrows | nlib::wkTab | nlib::wkEnter | nlib::wkEscape | nlib::wkOthers);
	SetClientRect(nlib::Rect(0, 0, 434, 340));
	SetBorderStyle(nlib::fbsDialog);
	SetBorderButtons(nlib::fbbSystemMenu);

	Panel1 = new nlib::Panel();
	Panel1->SetBounds(MY_RECT(5, 7, 420, 215));	// 420 x 215
	Panel1->SetAnchors(nlib::caLeft | nlib::caTop | nlib::caRight);
	Panel1->SetTabOrder(3);
	Panel1->SetInnerBorderStyle(nlib::pbsRaisedSunken);
	Panel1->SetParent(this);

	Label1 = new nlib::Label();
	Label1->SetText(lt.GetTranslationFor(FCT_LOCALE1) );
	Label1->SetBounds(MY_RECT(14, 5, 375, 155));	// 375 x 155
	Label1->SetAnchors(nlib::caLeft | nlib::caTop | nlib::caRight | nlib::caBottom);
	Label1->SetWordWrap(true);
	Label1->SetParent(Panel1);

	Label2 = new nlib::Label();
	Label2->SetText(lt.GetTranslationFor(FCT_LOCALE2));
	Label2->SetBounds(MY_RECT(14, 86, 380, 113));	// 380 x 113
	Label2->SetAnchors(nlib::caLeft | nlib::caTop | nlib::caRight | nlib::caBottom);
	Label2->SetWordWrap(true);
	Label2->SetParent(Panel1);

	lblOldLocale = new nlib::Label();
	lblOldLocale->SetBounds(MY_RECT(22,239,154,15));
	lblOldLocale->SetAnchors(nlib::caLeft | nlib::caTop | nlib::caRight | nlib::caBottom);
	lblOldLocale->SetText(lt.GetTranslationFor(FCT_CURNAMELABEL));
	lblOldLocale->SetParent(this);

	lblCurLocaleName = new nlib::Label();
	lblCurLocaleName->SetBounds(MY_RECT(177,239,40,15));
	lblCurLocaleName->SetText(L"C");
	lblCurLocaleName->SetParent(this);

	lblNewLocale = new nlib::Label();
	lblNewLocale->SetBounds(MY_RECT(22,263,117,15));
	lblNewLocale->SetText(lt.GetTranslationFor(FCT_NEWNAMELABEL));
	lblNewLocale->SetParent(this);

	edtLocale = new nlib::Edit();
	edtLocale->SetBounds(MY_RECT(169,262,80,23));
	edtLocale->SetText(L"C");
	edtLocale->SetTabOrder(0);
	edtLocale->SetParent(this);

	btnSave = new nlib::Button();
	btnSave->SetBounds(MY_RECT(342,238, 73, 23));
	btnSave->SetText(lt.GetTranslationFor(FCT_SAVE));		 // L"&Save"
	btnSave->SetEnabled(false);
	btnSave->SetAnchors(nlib::caRight | nlib::caBottom);
	btnSave->SetTabOrder(2);
	btnSave->SetParent(this);

	btnCancel = new nlib::Button();
	btnCancel->SetBounds(MY_RECT(342,268, 75, 23));
	btnCancel->SetText(lt.GetTranslationFor(FCT_CANCEL));
	btnCancel->SetAnchors(nlib::caRight | nlib::caBottom);
	btnCancel->SetTabOrder(1);
	btnCancel->SetCancel(true);
	btnCancel->SetParent(this);

	btnCancel->OnClick = CreateEvent(this, &TfrmLocale::btnCancelClick);
	btnSave->OnClick = CreateEvent(this, &TfrmLocale::btnSaveClick);
	edtLocale->OnTextChanged = CreateEvent(this, &TfrmLocale::edtLocaleTextChanged);
}

TfrmLocale::TfrmLocale()
{
	InitializeFormAndControls(); /* Control initializations. Do not remove. */
	std::locale loc = std::cout.getloc();

	std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> converter;
	_wsLocName = converter.from_bytes(loc.name());
	lblCurLocaleName->SetText(_wsLocName);
	edtLocale->SetText	 (_wsLocName);
}

TfrmLocale::~TfrmLocale()
{
	/* Don't 'delete' the form. Call Destroy() instead which has access to the protected destructor. */
}

void TfrmLocale::Destroy()
{
	/* Controls are valid here, but not in the destructor. */
	/* ... Your code here ... */

	Form::Destroy();
}

std::wstring TfrmLocale::LocaleName() const
{
	return _wsLocName;
}

void TfrmLocale::btnSaveClick(void *sender, nlib::EventParameters param)
{
	_wsLocName = edtLocale->Text();
	SetModalResult(nlib::mrOk);
}

void TfrmLocale::btnCancelClick(void *sender, nlib::EventParameters param)
{
	SetModalResult(nlib::mrCancel);
}

void TfrmLocale::edtLocaleTextChanged(void* sender, nlib::EventParameters param)
{
	std::wstring ws = edtLocale->Text();
	btnSave->SetEnabled(ws != _wsLocName);
	// DEBUG
	nlib::Label* pl = Label1;
#ifdef _DEBUG
	wchar_t buf[2048];
	std::swprintf(buf, 2048, L"Label1:(%d, %d, %d, %d) (%d x %d)", pl->Left(), pl->Top(), pl->Right(), pl->Bottom(), pl->Width(), pl->Height());
	OutputDebugString(buf);
#endif
}

