#include "Stdafx_zoli.h"

#include "resource.h"
void MyLoadWindowIcon(nlib::Form* f);

using namespace nlib;
#include "translations.h"
#include "help.h"

TfrmHelp *frmHelp;



void TfrmHelp::InitializeFormAndControls() /* Control initialization function generated by the designer. Modifications will be lost. */
{
	/* Generated member initialization. Do not modify. */
	SetLeft(531);
	SetTop(566);
	SetText(lt.GetTranslationFor(FCT_HELPTITLE));
	GetFont().SetFamily(L"Tahoma");
	SetWantedKeyTypes(nlib::wkArrows | nlib::wkTab | nlib::wkEnter | nlib::wkEscape | nlib::wkOthers);
	SetShowPosition(nlib::fspActiveMonitorCenter);
	SetBorderStyle(nlib::fbsDialog);
	SetKeyPreview(true);
	SetClientRect(nlib::Rect(0, 0, 652, 472));

	MyLoadWindowIcon(this);

	Label1 = new nlib::Label();
	Label1->SetBounds(nlib::Rect(273, 15, 359, 34));
	Label1->SetText(L"FalconCalc");
	Label1->SetAnchors(nlib::caTop);
	Label1->GetFont().SetFamily(L"Tahoma");
	Label1->GetFont().SetSize(12);
	Label1->GetFont().SetBold(true);
	Label1->SetParentFont(false);
	Label1->SetParent(this);

	Label2 = new nlib::Label();
	Label2->SetBounds(nlib::Rect(224, 39, 425, 53));
	Label2->SetText(lt.GetTranslationFor(FCT_ABOUTLINE1));
	Label2->SetAnchors(nlib::caTop);
	Label2->GetFont().SetFamily(L"Tahoma");
	Label2->SetParentFont(false);
	Label2->SetParent(this);

	Label3 = new nlib::Label();
	Label3->SetBounds(nlib::Rect(8, 72, 644, 462));
	Label3->SetText(lt.GetHelpText());		
	Label3->SetAnchors(nlib::caLeft | nlib::caTop | nlib::caRight);
	Label3->GetFont().SetFamily(L"Tahoma");
	Label3->GetFont().SetSize(8);
	Label3->SetParentFont(false);
	Label3->SetAutoSize(false);
	Label3->SetWordWrap(true);
	Label3->SetParent(this);


	OnKeyDown = CreateEvent(this, &TfrmHelp::frmHelpKeyDown);
	OnClick = CreateEvent(this, &TfrmHelp::frmHelpClick);
	Label3->OnClick = CreateEvent(this, &TfrmHelp::Label3Click);
}

void TfrmHelp::Destroy()
{
	/* Controls are valid here, but not in the destructor. */
	/* ... Your code here ... */

	Form::Destroy();
}

TfrmHelp::TfrmHelp()
{
	InitializeFormAndControls();

	Label3->SetWidth(Width() - Label3->Left() * 2);
	Label3->SetText(lt.GetHelpText());
	(void)Label3->Handle();
	Label3->SetAutoSize(true);
    SetHeight( Label3->Top() + Label3->Height() +50);
}

TfrmHelp::~TfrmHelp()
{
	/* Don't 'delete' the form. Call Destroy() instead which has access to the protected destructor. */
}

void TfrmHelp::Label3Click(void *sender, nlib::EventParameters param)
{
    Close();
}

void TfrmHelp::frmHelpClick(void *sender, nlib::EventParameters param)
{
	Close();
}

void TfrmHelp::frmHelpKeyDown(void *sender, nlib::KeyParameters param)
{
	Close();
}
