#include "Stdafx_zoli.h"

#include "resource.h"
void MyLoadWindowIcon(nlib::Form* f);

using namespace nlib;
#include "help.h"

TfrmHelp *frmHelp;

void TfrmHelp::InitializeFormAndControls() /* Control initialization function generated by the designer. Modifications will be lost. */
{
	/* Generated member initialization. Do not modify. */
	SetLeft(531);
	SetTop(566);
	SetText(L"FalconCalc Help");
	GetFont().SetFamily(L"Tahoma");
	SetWantedKeyTypes(nlib::wkArrows | nlib::wkTab | nlib::wkEnter | nlib::wkEscape | nlib::wkOthers);
	SetShowPosition(nlib::fspActiveMonitorCenter);
	SetBorderStyle(nlib::fbsDialog);
	SetKeyPreview(true);
	SetClientRect(nlib::Rect(0, 0, 652, 472));

	MyLoadWindowIcon(this);

	Label1 = new nlib::Label();
	Label1->SetBounds(nlib::Rect(273, 15, 359, 34));
	Label1->SetText(L"FalconCalc");
	Label1->SetAnchors(nlib::caTop);
	Label1->GetFont().SetFamily(L"Tahoma");
	Label1->GetFont().SetSize(12);
	Label1->GetFont().SetBold(true);
	Label1->SetParentFont(false);
	Label1->SetParent(this);

	Label2 = new nlib::Label();
	Label2->SetBounds(nlib::Rect(224, 39, 425, 53));
	Label2->SetText(L"A handy little calculator for everyone");
	Label2->SetAnchors(nlib::caTop);
	Label2->GetFont().SetFamily(L"Tahoma");
	Label2->SetParentFont(false);
	Label2->SetParent(this);

	Label3 = new nlib::Label();
	Label3->SetBounds(nlib::Rect(8, 72, 644, 462));
	Label3->SetText(L"Label3");
	Label3->SetAnchors(nlib::caLeft | nlib::caTop | nlib::caRight);
	Label3->GetFont().SetFamily(L"Tahoma");
	Label3->GetFont().SetSize(8);
	Label3->SetParentFont(false);
	Label3->SetAutoSize(false);
	Label3->SetWordWrap(true);
	Label3->SetParent(this);


	OnKeyDown = CreateEvent(this, &TfrmHelp::frmHelpKeyDown);
	OnClick = CreateEvent(this, &TfrmHelp::frmHelpClick);
	Label3->OnClick = CreateEvent(this, &TfrmHelp::Label3Click);
}

void TfrmHelp::Destroy()
{
	/* Controls are valid here, but not in the destructor. */
	/* ... Your code here ... */

	Form::Destroy();
}

TfrmHelp::TfrmHelp()
{
	InitializeFormAndControls();
	wchar_t* text = L"Every Windows has a desktop calculator with many features but FalconCalc offers many unique features not found in them:\n\n"
                    L"FalconCalc continuously evaluates expressions as they are entered. Those may contain built-in and user defined constants\n"
					L"and functions of any number of arguments with many important digits (currently 65, but can be any number).\n\n"

                    L"Results are displayed simultaneously as decimal, hexadecimal, octal and binary numbers and as a string of characters.\n\n"
                    L"By pressing the corresponding button the result can be copied to the clipboard in any of theses formats.\n\n"
                    L"Arithmetic formulas may contain the following operators:\n"
                    L"+, -, *, /, ^(power), | (or 'or'), & (or 'and'), xor, << (or 'shl'=shift left), << (or 'shr'=shift right),\n"
                    L" % (or mod - remainder), '~' bit negation\n\n"
					L"Logical operators:\n"
                    L"==, != (not equal), <, >, <=, >= (these results in 1 or 0)\n\n"
                    L"Built-in functions (alternative names in parenthesis)\n"
					L"abs, arcsin(asin), arccos(acos), arctan(atan), cos, cosh(ch), coth(cth), exp, fact, frac, int,\n"
					L"log(ln), log2, log10(lg), round, sign, sin, sinh(sh), sqrt, tan(tg), trunc\n\n"
					L"Built in mathematical constants:\n"
                    L"e (base of the natural logarithm), log2e (base 2 logarithm of e), log10e (or lge - base\n"
					L"10 logarithm of e), ln2 (natural logarithm of 2)\n"
					L"pi(or π), pi2 (π/2), pi4 (π/4), ppi (1/π), tpi (2/√π), sqpi (√π), \n"
					L"sqrt2 (√2), psqrt2 (1/√2)), sqrt3 (√3), sqrt3P2 (√3/2)\n\n"
                    L"Built-in physical constants:\n"
                    L"au - astronomical unit [m], c - speed of light in vacuum (definition - exact value) [m/s], \n"
                    L"h  - Planck constant  [Js], hbar - reduced Planck constant [Js], \n"
                    L"qe - elementary charge [As], me - electron mass [kg], mp - proton mass [kg], \n"
                    L"u - atomic mass unit [1], k - Boltzmann constant [J/K],G  - Newtonian constant of gravitation [m^3/kg/s^2],\n"
                    L"gf - mean value of the gravitational acceleration on Earth (9.81 m/s²)\n"
                    L"eps0 - electric constant (vacuum permittivity) exact value [F /m]\n"
                    L"mu0  - magnetic constant (vacuum permeability) exact value [N/A^2] = 4π·10^(-7), \n"
                    L"kc  - Coulomb's constant 1/4π eps0 [N m^2/C^2], LA  - Avogadro's number [1/mol],\n"
                    L"rf - Earth's radius [m], rg  - molar gas constant (8.31 J/ mol K), rs - Sun's radius\n"
                    L"u - atomic mass unit\n\n"
                    L"Any number of user constants and functions may be defined with any valid arithmetic formula including other constants and variables:\n\n"
                    L"Line format:   name = expression:comment:unit, where name may be a variable name or a function name like 'a(x,y)'\n\n"
					L"Examples:\n"
					L"      constR=8.31446261815324:Universal gas constant:J/K/mol\n"
					L"      solvequad(a, b, c, s) = (-b + s * sqrt(b ^ 2 - 4 * a * c)) / 2 / a:solves the quadratic equation ax² + bx + c = 0\n\n"
                    L"When a variable is modified the value of all dependent variables and functions are automatically changed\n"
                    L"Functions may have any number of arguments with any names that is different from the name of any built-in function or constant.\n";

	Label3->SetWidth(Width() - Label3->Left() * 2);
	Label3->SetText(text);
	(void)Label3->Handle();
	Label3->SetAutoSize(true);
    SetHeight( Label3->Top() + Label3->Height() +50);
}

TfrmHelp::~TfrmHelp()
{
	/* Don't 'delete' the form. Call Destroy() instead which has access to the protected destructor. */
}

void TfrmHelp::Label3Click(void *sender, nlib::EventParameters param)
{
    Close();
}

void TfrmHelp::frmHelpClick(void *sender, nlib::EventParameters param)
{
	Close();
}

void TfrmHelp::frmHelpKeyDown(void *sender, nlib::KeyParameters param)
{
	Close();
}
