#include "StdAfx_zoli.h"
#include "resource.h"
#include "wcommon.h"
using namespace nlib;
#include "mainForm.h"
#ifndef QTSA_PROJECT
	#include "SmartString.h"
#else
	#include "SmartStringQt.h"
#endif
#include "history.h"
#include "clipboard.h"

TfrmHistory *frmHistory;
extern Clipboard* MyClipboard;

using SmString::SmartString;

void TfrmHistory::InitializeFormAndControls() /* Control initialization function generated by the designer. Modifications will be lost. */
{
	/* Generated member initialization. Do not modify. */
	SetLeft(454);
	SetTop(1090);
	SetText(L"FalconCalc History");
	GetFont().SetFamily(L"Tahoma");
	SetWantedKeyTypes(nlib::wkArrows | nlib::wkTab | nlib::wkEnter | nlib::wkEscape | nlib::wkOthers);
	SetKeyPreview(true);
	SetClientRect(nlib::Rect(0, 0, 528, 183));

	MyLoadWindowIcon(this);

	lstHistory = new nlib::Listbox();
	lstHistory->SetBounds(nlib::Rect(8, 8, 440, 166));
	lstHistory->SetText(L"lstHistory");
	lstHistory->SetAnchors(nlib::caLeft | nlib::caTop | nlib::caRight | nlib::caBottom);
	lstHistory->SetTabOrder(0);
	lstHistory->SetItemHeight(14);
	lstHistory->SetParent(this);

	btnDelete = new nlib::ToolButton();
	btnDelete->SetBounds(nlib::Rect(445, 8, 468, 30));
	btnDelete->SetAnchors(nlib::caTop | nlib::caRight);
	btnDelete->SetTabOrder(1);
	btnDelete->GetFont().SetFamily(L"Tahoma");
	btnDelete->GetFont().SetColor(nlib::clRed);
	btnDelete->GetFont().SetSize(18);
	btnDelete->SetParentFont(false);
	btnDelete->SetColor(nlib::Color(255, 0, 0));
	btnDelete->SetParentColor(false);
	btnDelete->SetTabOrder(1);
	btnDelete->SetImagePosition(nlib::bipCenter);
	btnDelete->SetFlat(false);
	btnDelete->SetParent(this);

	btnClear = new nlib::ToolButton();
	btnClear->SetBounds(nlib::Rect(445, 36, 468, 58));
	btnClear->SetAnchors(nlib::caTop | nlib::caRight);
	btnClear->SetTabOrder(2);
	btnClear->SetImagePosition(nlib::bipCenter);
	btnClear->SetFlat(false);
	btnClear->SetParent(this);

	chkSorted = new nlib::Checkbox();
	chkSorted->SetBounds(nlib::Rect(448, 104, 522, 120));
	chkSorted->SetText(L"&Sort");
	chkSorted->SetAnchors(nlib::caTop | nlib::caRight);
	chkSorted->SetTabOrder(3);
	chkSorted->SetParent(this);

	btnCancel = new nlib::Button();
	btnCancel->SetBounds(nlib::Rect(446, 145, 521, 168));
	btnCancel->SetText(L"&Dismiss");
	btnDelete->SetText(L"–");
	btnCancel->SetAnchors(nlib::caRight | nlib::caBottom);
	btnCancel->GetFont().SetFamily(L"Tahoma");
	btnCancel->GetFont().SetSize(10);
	btnCancel->GetFont().SetCharacterSet(nlib::fcsAnsi);
	btnCancel->GetFont().SetOutputQuality(nlib::foqDraft);
	btnCancel->SetParentFont(false);
	btnCancel->SetTabOrder(4);
	btnCancel->SetParent(this);

	btnClear->Image()->SetBitmap(new nlib::Bitmap(NULL, MAKEINTRESOURCE(28682)));

	OnKeyPress = CreateEvent(this, &TfrmHistory::FormKeyPress);
	OnMove = CreateEvent(this, &TfrmHistory::FormMove);
	OnEndSizeMove = CreateEvent(this, &TfrmHistory::FormSizeMoveEnded);
	OnClose = CreateEvent(this, &TfrmHistory::FormClose);
	lstHistory->OnDblClick = CreateEvent(this, &TfrmHistory::lstHistoryDblClick);
	btnDelete->OnClick = CreateEvent(this, &TfrmHistory::btnDeleteClick);
	btnClear->OnClick = CreateEvent(this, &TfrmHistory::btnClearClick);
	chkSorted->OnClick = CreateEvent(this, &TfrmHistory::chkSortClick);
	btnCancel->OnClick = CreateEvent(this, &TfrmHistory::btnCancelClick);
}

void TfrmHistory::Destroy()
{
	/* Controls are valid here, but not in the destructor. */
	/* ... Your code here ... */

	Form::Destroy();
}

TfrmHistory::TfrmHistory()
{
	InitializeFormAndControls();
}

TfrmHistory::~TfrmHistory()
{
	/* Don't 'delete' the form. Call Destroy() instead which has access to the protected destructor. */
	frmHistory = NULL;
}

void TfrmHistory::lstHistoryDblClick(void *sender, nlib::MouseButtonParameters param)
{
    if(lstHistory->ItemIndex() >= 0)
    {
        int n;
        if( (n = lstHistory->ItemIndex()) >= 0)
        {
            frmMain->cbInfix->SetText(lstHistory->Items().Text(n));
            frmMain->Focus();
        }
    }
}

void TfrmHistory::btnCancelClick(void *sender, nlib::EventParameters param)
{
	Close();
}

void TfrmHistory::btnClearClick(void *sender, nlib::EventParameters param)
{
    lstHistory->Clear();
    frmMain->slHistory.clear();
}

void TfrmHistory::btnDeleteClick(void *sender, nlib::EventParameters param)
{
    int n = lstHistory->ItemIndex();
    if(n >=0)
    {
		lstHistory->Items().Delete(n);
		frmMain->slHistory.Delete(n);
    }
}


void TfrmHistory::FormKeyPress(void *sender, nlib::KeyPressParameters param)
{
    SmartString s;

	switch (param.key)
	{
		case '1': 
		case '2':
			if (param.vkeys & vksAlt)	// functions or variables
			{
				nlib::EventParameters par;
				frmMain->OpenVarsOrFunctions(nullptr, param.key - '0', par);
			}
			break;
		case 22:						// paste CTRL + V
			s = MyClipboard->GetText();		 // MyClipboard must exist!
			if(s.empty())
				break;
			frmMain->slHistory.Add(s);
			lstHistory->Items().SetLines(frmMain->slHistory.ToWstringVector());
			break;
		case 3:
			for(int i =0; i < lstHistory->Items().Count(); ++i)
				s += lstHistory->Items().Text(i) + L"\n";
			MyClipboard->SetText(s.ToWideString());
			break;
		case VK_RETURN:
			if(lstHistory->ItemIndex() >= 0)
			{
				int n;
				if( (n = lstHistory->ItemIndex()) >= 0)
				{
					frmMain->cbInfix->SetText(lstHistory->Items().Text(n)) ;
					frmMain->Focus();
				}
			}
		case VK_ESCAPE:
			Close();
			break;
		default:
			break;
	}
}

void TfrmHistory::FormClose(void *sender, nlib::FormCloseParameters param)
{
    param.action = caDeleteForm;
	frmHistory=NULL;
	SetFocus(frmMain->Handle());
}
void TfrmHistory::chkSortClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmHistory::FormMove(void *sender, nlib::EventParameters param)
{
	if (!frmMain->InMoving() && !_busy && GetSnapSide() != FalconCalc::wsNone)
		Snap();
}

void TfrmHistory::FormSizeMoveEnded(void* sender, nlib::SizePositionChangedParameters param)
{
	if (!frmMain->InMoving() && !_busy && GetSnapSide() != FalconCalc::wsNone)
		Snap();
/*
#if defined(_DEBUG)
	static char * s[] = {
						 "snapped at top",
						 "snapped at right",
						 "snapped at bottom",
						 "snapped at left"
					   };
	std::string dbgs = std::string("History: ") + std::string((_snappedToSide == FalconCalc::wsNone ? "unsnapped" : s[(int)_snappedToSide - 1]));
	OutputDebugStringA(dbgs.c_str());

#endif	*/
}

FalconCalc::WindowSide TfrmHistory::GetSnapSide()
{
	// determine snap area index
	RECT r = wiHist.BareVisibleWindowRect();
	_snapDist = _snapPixelLimit;
	return _snappedToSide = ::GetSnapSide(r, _snapDist);
}

void TfrmHistory::Snap()
{
	RECT rbase = wiMain.BareVisibleWindowRect(),
			dr = wiHist.BareVisibleWindowRect();

	POINT pt = WinDistance(rbase, dr, _snappedToSide);
	rbase = wiMain.WindowRect();
	dr = wiHist.WindowRect();

	if (::SnapTo(dr, _snappedToSide, WinDistance(rbase, dr, _snappedToSide) ))	// get snap displacement into 'dr'
	{
		++_busy;
		MoveWindow(Handle(), dr.left, dr.top, dr.right - dr.left, dr.bottom - dr.top, true);
		--_busy;
	}
}

