#include "Stdafx_zoli.h"
#include "stdafx_lc.h"

using namespace nlib;
#include "histopt.h"

TfrmHistOptions *frmHistOptions;

void TfrmHistOptions::InitializeFormAndControls() /* Control initialization function generated by the designer. Modifications will be lost. */
{
	/* Generated member initialization. Do not modify. */
	SetLeft(300);
	SetTop(523);
	SetText(L"FalconCalc - History options");
	GetFont().SetFamily(L"Tahoma");
	SetWantedKeyTypes(nlib::wkArrows | nlib::wkTab | nlib::wkEnter | nlib::wkEscape | nlib::wkOthers);
	SetShowPosition(nlib::fspActiveMonitorCenter);
	SetBorderStyle(nlib::fbsSingle);
	SetClientRect(nlib::Rect(0, 0, 284, 159));

	chkDepth = new nlib::Checkbox();
	chkDepth->SetBounds(nlib::Rect(16, 32, 161, 48));
	chkDepth->SetText(L"Maximum History &Depth:");
	chkDepth->SetTabOrder(0);
	chkDepth->SetParent(this);

	chkAutoSave = new nlib::Checkbox();
	chkAutoSave->SetBounds(nlib::Rect(16, 56, 174, 72));
	chkAutoSave->SetText(L"&Time of automatic saves:");
	chkAutoSave->SetTabOrder(1);
	chkAutoSave->SetParent(this);

	chkSort = new nlib::Checkbox();
	chkSort->SetBounds(nlib::Rect(16, 80, 96, 96));
	chkSort->SetText(L"&Sorted");
	chkSort->SetTabOrder(2);
	chkSort->SetParent(this);

	spinDepth = new nlib::Edit();
	spinDepth->SetBounds(nlib::Rect(176, 32, 256, 53));
	spinDepth->SetText(L"100");
	spinDepth->SetTabOrder(3);
	spinDepth->SetParent(this);

	spinDepthBtn = new nlib::UpDown();
	spinDepthBtn->SetBounds(nlib::Rect(255, 32, 272, 53));
	spinDepthBtn->SetMinValue(1);
	spinDepthBtn->SetMaxValue(9999);
	spinDepthBtn->SetPosition(100);
	spinDepthBtn->SetParent(this);

	edtInterval = new nlib::Edit();
	edtInterval->SetBounds(nlib::Rect(176, 56, 256, 77));
	edtInterval->SetText(L"00:00:10");
	edtInterval->SetTabOrder(4);
	edtInterval->SetParent(this);

	btnOk = new nlib::Button();
	btnOk->SetBounds(nlib::Rect(184, 96, 259, 119));
	btnOk->SetText(L"Ok");
	btnOk->SetTabOrder(5);
	btnOk->SetParent(this);

	btnCancel = new nlib::Button();
	btnCancel->SetBounds(nlib::Rect(184, 120, 259, 143));
	btnCancel->SetText(L"Cancel");
	btnCancel->SetTabOrder(6);
	btnCancel->SetCancel(true);
	btnCancel->SetParent(this);

	SetActiveControl(btnOk);
	spinDepthBtn->SetAttachedEditor(spinDepth);

	chkDepth->OnClick = CreateEvent(this, &TfrmHistOptions::chkDepthClick);
	chkAutoSave->OnClick = CreateEvent(this, &TfrmHistOptions::chkAutoSaveClick);
	chkSort->OnClick = CreateEvent(this, &TfrmHistOptions::chkSortClick);
	edtInterval->OnKeyDown = CreateEvent(this, &TfrmHistOptions::edtIntervalKeyDown);
	btnOk->OnClick = CreateEvent(this, &TfrmHistOptions::btnOkClick);
	btnCancel->OnClick = CreateEvent(this, &TfrmHistOptions::btnCancelClick);
}

void TfrmHistOptions::Destroy()
{
	/* Controls are valid here, but not in the destructor. */
	/* ... Your code here ... */

	Form::Destroy();
}

TfrmHistOptions::TfrmHistOptions()
{
	InitializeFormAndControls();
}

TfrmHistOptions::~TfrmHistOptions()
{
	/* Don't 'delete' the form. Call Destroy() instead which has access to the protected destructor. */
}

void TfrmHistOptions::Setup(size_t depth, size_t timeout, bool sorted)
{
    chkDepth->SetChecked( depth > 0);
	std::wstringstream wss;
	wss << depth;
	spinDepth->SetText(depth > 0 ? wss.str() : L"100");

	wss.clear(); wss.str(L"");	// clear content

	spinDepthBtn->SetPosition(depth > 0 ? depth : 100);
    spinDepthBtn->SetEnabled(chkDepth->Checked());
    spinDepth->SetEnabled(chkDepth->Checked());
    chkAutoSave->SetChecked( timeout > 0);
    chkAutoSave->SetEnabled(chkAutoSave->Checked());

    int h = timeout/3600,
        m = (timeout/60) % 60,
        s = timeout ? (timeout % 60) : 10;	// for 0 timeout
	wss << h << TimeSeparator() << m << TimeSeparator() << s;
	edtInterval->SetText(wss.str() );
	
	chkSort->SetChecked(sorted);
}

void TfrmHistOptions::btnCancelClick(void *sender, nlib::EventParameters param)
{
	SetModalResult(mrCancel);
}

void TfrmHistOptions::btnOkClick(void *sender, nlib::EventParameters param)
{
	SetModalResult(mrOk);
}

void TfrmHistOptions::chkAutoSaveClick(void *sender, nlib::EventParameters param)
{
    edtInterval->SetEnabled( chkAutoSave->Checked());
}

void TfrmHistOptions::chkDepthClick(void *sender, nlib::EventParameters param)
{
    spinDepth->SetEnabled( chkDepth->Checked());
}

wchar_t TimeSeparator()
{
	return L':';
}

void TfrmHistOptions::edtIntervalKeyDown(void *sender, nlib::KeyParameters param)
{
    if(param.keycode != TimeSeparator() && param.keycode != VK_LEFT && param.keycode != VK_RIGHT && param.keycode != VK_LEFT &&
       param.keycode != VK_BACK && param.keycode != VK_DELETE && (param.keycode < '0' || param.keycode > '9'))
    {
        param.keycode = 0;
        return;
    }
}

void TfrmHistOptions::chkSortClick(void *sender, nlib::EventParameters param)
{
    ;
}
