#include "Stdafx_zoli.h"
#include "stdafx_lc.h"

using namespace nlib;

#include "resource.h"
void MyLoadWindowIcon(nlib::Form* f);

#include "histopt.h"

TfrmHistOptions *frmHistOptions;

void TfrmHistOptions::InitializeFormAndControls() /* Control initialization function generated by the designer. Modifications will be lost. */
{
	/* Generated member initialization. Do not modify. */
	SetLeft(638);
	SetTop(417);
	SetText(L"FalconCalc - History options");
	GetFont().SetFamily(L"Tahoma");
	SetWantedKeyTypes(nlib::wkArrows | nlib::wkTab | nlib::wkEnter | nlib::wkEscape | nlib::wkOthers);
	SetShowPosition(nlib::fspActiveMonitorCenter);
	SetBorderStyle(nlib::fbsSingle);
	SetClientRect(nlib::Rect(0, 0, 340, 192));

	MyLoadWindowIcon(this);

	chkDepth = new nlib::Checkbox();
	chkDepth->SetBounds(nlib::Rect(16, 32, 161, 48));
	chkDepth->SetText(L"Maximum History &Depth:");
	chkDepth->SetTabOrder(0);
	chkDepth->SetParent(this);

	spinDepth = new nlib::Edit();
	spinDepth->SetBounds(nlib::Rect(176, 32, 256, 53));
	spinDepth->SetText(L"100");
	spinDepth->SetTabOrder(1);
	spinDepth->SetParent(this);

	spinDepthBtn = new nlib::UpDown();
	spinDepthBtn->SetBounds(nlib::Rect(255, 32, 272, 53));
	spinDepthBtn->SetMinValue(1);
	spinDepthBtn->SetMaxValue(9999);
	spinDepthBtn->SetPosition(100);
	spinDepthBtn->SetParent(this);

	chkAutoSave = new nlib::Checkbox();
	chkAutoSave->SetBounds(nlib::Rect(16, 56, 174, 72));
	chkAutoSave->SetText(L"Sa&ve after this interval:");
	chkAutoSave->SetTabOrder(2);
	chkAutoSave->SetParent(this);

	edtInterval = new nlib::Edit();
	edtInterval->SetBounds(nlib::Rect(176, 56, 256, 77));
	edtInterval->SetText(L"00:00:10");
	edtInterval->SetTabOrder(3);
	edtInterval->SetParent(this);

	Label2 = new nlib::Label();
	Label2->SetBounds(nlib::Rect(18, 89, 166, 103));
	Label2->SetText(L"&Min. length to save: (0:any):");
	Label2->SetParent(this);

	edtMinLength = new nlib::Edit();
	edtMinLength->SetBounds(nlib::Rect(176, 85, 256, 107));
	edtMinLength->SetText(L"0");
	edtMinLength->SetTabOrder(4);
	edtMinLength->SetParent(this);

	sbMinLength = new nlib::UpDown();
	sbMinLength->SetBounds(nlib::Rect(255, 85, 272, 107));
	sbMinLength->SetParent(this);

	chkSort = new nlib::Checkbox();
	chkSort->SetBounds(nlib::Rect(16, 144, 96, 160));
	chkSort->SetText(L"&Sorted");
	chkSort->SetTabOrder(5);
	chkSort->SetParent(this);

	btnOk = new nlib::Button();
	btnOk->SetBounds(nlib::Rect(248, 128, 323, 151));
	btnOk->SetText(L"&Ok");
	btnOk->SetTabOrder(6);
	btnOk->SetParent(this);

	btnCancel = new nlib::Button();
	btnCancel->SetBounds(nlib::Rect(248, 152, 323, 175));
	btnCancel->SetText(L"Cance&l");
	btnCancel->SetTabOrder(7);
	btnCancel->SetCancel(true);
	btnCancel->SetParent(this);

	Label1 = new nlib::Label();
	Label1->SetBounds(nlib::Rect(261, 59, 327, 73));
	Label1->SetText(L"(HH:MM:SS)");
	Label1->SetParent(this);

	SetActiveControl(btnOk);
	spinDepthBtn->SetAttachedEditor(spinDepth);
	sbMinLength->SetAttachedEditor(edtMinLength);

	chkDepth->OnClick = CreateEvent(this, &TfrmHistOptions::chkDepthClick);
	chkAutoSave->OnClick = CreateEvent(this, &TfrmHistOptions::chkAutoSaveClick);
	chkSort->OnClick = CreateEvent(this, &TfrmHistOptions::chkSortClick);
	edtInterval->OnKeyPress = CreateEvent(this, &TfrmHistOptions::edtIntervalKeyPressed);
	spinDepth->OnKeyPress = CreateEvent(this, &TfrmHistOptions::edtIntervalKeyPressed);
	edtMinLength->OnKeyPress = CreateEvent(this, &TfrmHistOptions::edtMinLengthKeyPressed);
	btnOk->OnClick = CreateEvent(this, &TfrmHistOptions::btnOkClick);
	btnCancel->OnClick = CreateEvent(this, &TfrmHistOptions::btnCancelClick);
}

void TfrmHistOptions::Destroy()
{
	/* Controls are valid here, but not in the destructor. */
	/* ... Your code here ... */

	Form::Destroy();
}

TfrmHistOptions::TfrmHistOptions()
{
	InitializeFormAndControls();
}

TfrmHistOptions::~TfrmHistOptions()
{
	/* Don't 'delete' the form. Call Destroy() instead which has access to the protected destructor. */
}

void TfrmHistOptions::Setup(size_t depth, size_t timeout, bool sorted, int minLength)
{
    chkDepth->SetChecked( depth > 0);
	spinDepth->SetText(depth > 0 ? to_wstring(depth) : L"100");

	spinDepthBtn->SetPosition(depth > 0 ? depth : 100);
    spinDepthBtn->SetEnabled(chkDepth->Checked());
    spinDepth->SetEnabled(chkDepth->Checked());
    chkAutoSave->SetChecked( timeout > 0);
//    chkAutoSave->SetEnabled(chkAutoSave->Checked());

    int h = timeout/3600,
        m = (timeout/60) % 60,
        s = timeout ? (timeout % 60) : 10;	// for 0 timeout
	std::wstring ws =  to_wstring(h) + TimeSeparator() + to_wstring(m)  + TimeSeparator() + to_wstring(s);
	edtInterval->SetText(ws);
	
	chkSort->SetChecked(sorted);

	edtMinLength->SetText(to_wstring(minLength));
}

void TfrmHistOptions::btnCancelClick(void *sender, nlib::EventParameters param)
{
	SetModalResult(mrCancel);
}

void TfrmHistOptions::btnOkClick(void *sender, nlib::EventParameters param)
{
	SetModalResult(mrOk);
}
void TfrmHistOptions::edtSpinDepthKeyPressed(void* sender, nlib::KeyPressParameters param)
{
	_DropInvalidKeys(param);
}

void TfrmHistOptions::chkAutoSaveClick(void *sender, nlib::EventParameters param)
{
    // edtInterval->SetEnabled( chkAutoSave->Checked());
}

void TfrmHistOptions::chkDepthClick(void *sender, nlib::EventParameters param)
{
    spinDepth->SetEnabled( chkDepth->Checked());
}

wchar_t TimeSeparator()
{
	return L':';
}

void TfrmHistOptions::_DropInvalidKeys(nlib::KeyParameters& param)
{
    if(param.keycode != TimeSeparator() && param.keycode != VK_LEFT && param.keycode != VK_RIGHT && param.keycode != VK_LEFT &&
       param.keycode != VK_BACK && param.keycode != VK_DELETE && (param.keycode < '0' || param.keycode > '9'))
    {
        param.keycode = 0;
        return;
    }
}
																		 
void TfrmHistOptions::_DropInvalidKeys(nlib::KeyPressParameters& param)
{
    if(param.key != TimeSeparator() && param.key != VK_LEFT && param.key != VK_RIGHT && param.key != VK_LEFT &&
       param.key != VK_BACK && param.key != VK_DELETE && (param.key < '0' || param.key > '9'))
    {
        param.key = 0;
        return;
    }
}

void TfrmHistOptions::edtIntervalKeyPressed(void* sender, nlib::KeyPressParameters param)
{
	_DropInvalidKeys(param);
}

void TfrmHistOptions::edtMinLengthKeyPressed(void* sender, nlib::KeyPressParameters param)
{
	_DropInvalidKeys(param);
}

void TfrmHistOptions::chkSortClick(void *sender, nlib::EventParameters param)
{
    ;
}
