#include "Stdafx_zoli.h"
#include "stdafx_lc.h"

using namespace nlib;

#include "resource.h"
void MyLoadWindowIcon(nlib::Form* f);

#include "common.h"
#include "translations.h"
#include "histopt.h"

TfrmHistOptions *frmHistOptions;

void TfrmHistOptions::InitializeFormAndControls() /* Control initialization function generated by the designer. Modifications will be lost. */
{
	/* Generated member initialization. Do not modify. */
	SetLeft(638);
	SetTop(417);
	SetText(L"FalconCalc - History options");
	GetFont().SetFamily(L"Tahoma");
	SetWantedKeyTypes(nlib::wkArrows | nlib::wkTab | nlib::wkEnter | nlib::wkEscape | nlib::wkOthers);
	SetShowPosition(nlib::fspActiveMonitorCenter);
	SetBorderStyle(nlib::fbsSingle);
	SetClientRect(nlib::Rect(0, 0, 425, 243));

	MyLoadWindowIcon(this);

	Panel1 = new nlib::Panel();
	Panel1->SetBounds(nlib::Rect(8, 8, 416, 168));
	Panel1->SetTabOrder(2);
	Panel1->SetInnerBorderStyle(nlib::pbsRaisedSunken);
	Panel1->SetParent(this);

	chkDepth = new nlib::Checkbox();
	chkDepth->SetBounds(nlib::Rect(24, 32, 221, 48));
	chkDepth->SetText(lt.GetTranslationFor(FCT_MAXHISTDEPTH));
	chkDepth->SetTooltipText(lt.GetTranslationFor(FCT_MAXHISTDEPTHTIP));
	chkDepth->SetTabOrder(0);
	chkDepth->SetParent(this);

	spinDepth = new nlib::Edit();
	spinDepth->SetBounds(nlib::Rect(223, 32, 303, 53));
	spinDepth->SetText(L"20");
	spinDepth->SetTabOrder(1);
	spinDepth->SetParent(this);

	spinDepthBtn = new nlib::UpDown();
	spinDepthBtn->SetBounds(nlib::Rect(302, 32, 319, 53));
	spinDepthBtn->SetMinValue(1);
	spinDepthBtn->SetMaxValue(9999);
	spinDepthBtn->SetPosition(100);
	spinDepthBtn->SetParent(this);

	chkAutoSave = new nlib::Checkbox();
	chkAutoSave->SetBounds(nlib::Rect(24, 56, 206, 72));
	chkAutoSave->SetText(lt.GetTranslationFor(FCT_AUTOSAVE));
	chkAutoSave->SetTabOrder(2);
	chkAutoSave->SetTooltipText(lt.GetTranslationFor(FCT_AUTOSAVETIP));
	chkAutoSave->SetParent(this);

	edtInterval = new nlib::Edit();
	edtInterval->SetBounds(nlib::Rect(223, 56, 302, 77));
	edtInterval->SetText(L"00:00:10");
	edtInterval->SetTabOrder(3);
	edtInterval->SetParent(this);

	Label1 = new nlib::Label();
	Label1->SetBounds(nlib::Rect(328, 59, 394, 73));
	Label1->SetText(lt.GetTranslationFor(FCT_HHMMSS));
	Label1->SetParent(this);

	Label2 = new nlib::Label();
	Label2->SetBounds(nlib::Rect(26, 89, 200, 103));
	Label2->SetText(lt.GetTranslationFor(FCT_HISTMINLENGTHLABEL));
	Label2->SetTooltipText(lt.GetTranslationFor(FCT_HISTMINLENGTHTIP));
	Label2->SetParent(this);

	edtMinLength = new nlib::Edit();
	edtMinLength->SetBounds(nlib::Rect(223, 85, 303, 107));
	edtMinLength->SetText(L"0");
	edtMinLength->SetTabOrder(4);
	edtMinLength->SetParent(this);

	lblNone = new nlib::Label();
	lblNone->SetBounds(nlib::Rect(318, 80, 391, 102));
	lblNone->SetText(lt.GetTranslationFor(FCT_HISTMINLENGTHSAVEALL));
	lblNone->SetParent(Panel1);

	sbMinLength = new nlib::UpDown();
	sbMinLength->SetBounds(nlib::Rect(302, 85, 319, 107));
	sbMinLength->SetParent(this);

	chkSort = new nlib::Checkbox();
	chkSort->SetBounds(nlib::Rect(24, 120, 144, 136));
	chkSort->SetText(lt.GetTranslationFor(FCT_HISTSORTED));
	chkSort->SetTabOrder(5);
	chkSort->SetParent(this);

	cbClearHist = new nlib::Checkbox();
	//cbClearHist->SetBounds(nlib::Rect(224, 120, 376, 136));
	cbClearHist->SetBounds(nlib::Rect(150, 112, 302, 128));
	cbClearHist->SetText(lt.GetTranslationFor(FCT_HISTCLEAR));
	cbClearHist->SetTabOrder(5);
	cbClearHist->SetParent(Panel1);

	btnOk = new nlib::Button();
	btnOk->SetBounds(nlib::Rect(328, 179, 403, 202));
	btnOk->SetText(lt.GetTranslationFor(FCT_OK));
	btnOk->SetTabOrder(6);
	btnOk->SetAnchors(nlib::caRight | nlib::caBottom);
	btnOk->SetParent(this);

	btnCancel = new nlib::Button();
	btnCancel->SetBounds(nlib::Rect(328, 203, 403, 226));
	btnCancel->SetAnchors(nlib::caRight | nlib::caBottom);
	btnCancel->SetText(lt.GetTranslationFor(FCT_CANCEL));
	btnCancel->SetTabOrder(7);
	btnCancel->SetCancel(true);
	btnCancel->SetParent(this);

	SetActiveControl(btnOk);
	spinDepthBtn->SetAttachedEditor(spinDepth);
	sbMinLength->SetAttachedEditor(edtMinLength);

	cbClearHist->OnClick = CreateEvent(this, &TfrmHistOptions::cbClearHistClick);
	btnCancel->OnClick = CreateEvent(this, &TfrmHistOptions::btnCancelClick);
	btnOk->OnClick = CreateEvent(this, &TfrmHistOptions::btnOkClick);
	chkAutoSave->OnClick = CreateEvent(this, &TfrmHistOptions::chkAutoSaveClick);
	chkDepth->OnClick = CreateEvent(this, &TfrmHistOptions::chkDepthClick);
	chkSort->OnClick = CreateEvent(this, &TfrmHistOptions::chkSortClick);
	edtInterval->OnKeyPress = CreateEvent(this, &TfrmHistOptions::edtIntervalKeyPressed);
	edtMinLength->OnKeyPress = CreateEvent(this, &TfrmHistOptions::edtMinLengthKeyPressed);
	spinDepth->OnKeyPress = CreateEvent(this, &TfrmHistOptions::edtIntervalKeyPressed);
}

void TfrmHistOptions::Destroy()
{
	/* Controls are valid here, but not in the destructor. */
	/* ... Your code here ... */

	Form::Destroy();
}

TfrmHistOptions::TfrmHistOptions()
{
	InitializeFormAndControls();
}

TfrmHistOptions::~TfrmHistOptions()
{
	/* Don't 'delete' the form. Call Destroy() instead which has access to the protected destructor. */
}

void TfrmHistOptions::Setup(size_t depth, size_t timeout, bool sorted, int minLength)
{
    chkDepth->SetChecked( depth > 0);
	spinDepth->SetText(depth > 0 ? std::to_wstring(depth) : L"100");

	spinDepthBtn->SetPosition(depth > 0 ? depth : 100);
    spinDepthBtn->SetEnabled(chkDepth->Checked());
    spinDepth->SetEnabled(chkDepth->Checked());
    chkAutoSave->SetChecked( timeout > 0);
//    chkAutoSave->SetEnabled(chkAutoSave->Checked());

    int h = timeout/3600,
        m = (timeout/60) % 60,
        s = timeout ? (timeout % 60) : 10;	// for 0 timeout
	std::wstring ws =  std::to_wstring(h) + TimeSeparator() + std::to_wstring(m)  + TimeSeparator() + std::to_wstring(s);
	edtInterval->SetText(ws);
	
	chkSort->SetChecked(sorted);

	edtMinLength->SetText(std::to_wstring(minLength));
}

void TfrmHistOptions::btnCancelClick(void *sender, nlib::EventParameters param)
{
	SetModalResult(mrCancel);
}

void TfrmHistOptions::btnOkClick(void *sender, nlib::EventParameters param)
{
	SetModalResult(mrOk);
}
void TfrmHistOptions::cbClearHistClick(void* sender, nlib::EventParameters param)
{
	_clearhistory = cbClearHist->Checked();
}
void TfrmHistOptions::edtSpinDepthKeyPressed(void* sender, nlib::KeyPressParameters param)
{
	_DropInvalidKeys(param);
}

void TfrmHistOptions::chkAutoSaveClick(void *sender, nlib::EventParameters param)
{
    // edtInterval->SetEnabled( chkAutoSave->Checked());
}

void TfrmHistOptions::chkDepthClick(void *sender, nlib::EventParameters param)
{
    spinDepth->SetEnabled( chkDepth->Checked());
}

wchar_t TimeSeparator()
{
	return L':';
}

void TfrmHistOptions::_DropInvalidKeys(nlib::KeyParameters& param)
{
    if(param.keycode != TimeSeparator() && param.keycode != VK_LEFT && param.keycode != VK_RIGHT && param.keycode != VK_LEFT &&
       param.keycode != VK_BACK && param.keycode != VK_DELETE && (param.keycode < '0' || param.keycode > '9'))
    {
        param.keycode = 0;
        return;
    }
}
																		 
void TfrmHistOptions::_DropInvalidKeys(nlib::KeyPressParameters& param)
{
    if(param.key != TimeSeparator() && param.key != VK_LEFT && param.key != VK_RIGHT && param.key != VK_LEFT &&
       param.key != VK_BACK && param.key != VK_DELETE && (param.key < '0' || param.key > '9'))
    {
        param.key = 0;
        return;
    }
}

void TfrmHistOptions::edtIntervalKeyPressed(void* sender, nlib::KeyPressParameters param)
{
	_DropInvalidKeys(param);
}

void TfrmHistOptions::edtMinLengthKeyPressed(void* sender, nlib::KeyPressParameters param)
{
	_DropInvalidKeys(param);
}

void TfrmHistOptions::chkSortClick(void *sender, nlib::EventParameters param)
{
    ;
}
