#include "StdAfx.h"
#include "main.h"

TfrmMain *frmMain;

void TfrmMain::InitializeFormAndControls() /* Control initialization function generated by the designer. Modifications will be lost. */
{
	/* Generated member initialization. Do not modify. */
	SetLeft(435);
	SetTop(603);
	SetText(L"FalconCalc");
	GetFont().SetFamily(L"Tahoma");
	GetFont().SetSize(10);
	SetWantedKeyTypes(nlib::wkArrows | nlib::wkTab | nlib::wkEnter | nlib::wkEscape | nlib::wkOthers);
	SetShowPosition(nlib::fspActiveMonitorCenter);
	SetBorderStyle(nlib::fbsSingle);
	SetClientRect(nlib::Rect(0, 0, 528, 419 + GetSystemMetrics(SM_CYMENU)));

	FontDialog1 = new nlib::FontDialog();
	FontDialog1->GetFont().SetFamily(L"Tahoma");
	FontDialog1->GetFont().SetSize(8);
	FontDialog1->SetParent(this);

	mnuMain = new nlib::Menubar();
	miFile = mnuMain->Add(L"&File");
	miExit = miFile->Add(L"E&xit");
	miExit->SetShortcut(L"Alt+X");
	miEdit = mnuMain->Add(L"&Edit");
	miCopy = miEdit->Add(L"&Copy");
	miCopy->SetShortcutText(L"Ctrl+C");
	miPaste = miEdit->Add(L"&Paste");
	miPaste->SetShortcutText(L"Ctrl+V");
	miAppend = miEdit->Add(L"Paste &After");
	MenuItem1 = miEdit->Add(L"-");
	miCopyDecimal = miEdit->Add(L"Copy &Decimal");
	miCopyHexadecimal = miEdit->Add(L"Copy &Hexadecimal");
	miCopyHexadecimal->SetTag(1);
	miCopyOctal = miEdit->Add(L"Copy &Octal");
	miCopyOctal->SetTag(2);
	miCopyBinary = miEdit->Add(L"Copy &Binary");
	miCopyBinary->SetTag(3);
	MenuItem2 = miEdit->Add(L"-");
	MenuItem3 = miEdit->Add(L"-");
	MenuItem3->SetVisible(false);
	miClearHist = miEdit->Add(L"C&lear History");
	miView = mnuMain->Add(L"&View");
	miEditVars = miView->Add(L"Edit User &Variables...");
	miEditVars->SetTag(1);
	miEditVars->SetShortcut(L"Alt+1");
	miEditFuncs = miView->Add(L"Edit User &Functions...");
	miEditFuncs->SetShortcut(L"Alt+2");
	miShowHist = miView->Add(L"Edit &History");
	miShowHist->SetShortcut(L"Alt+3");
	miOptions = mnuMain->Add(L"&Options");
	miShowDecOpts = miOptions->Add(L"Show &Decimal Options");
	miShowDecOpts->SetShortcutText(L"Ctrl+D");
	miShowHexOpts = miOptions->Add(L"Show &Hexadecimal  Options");
	miShowHexOpts->SetShortcut(L"Ctrl+X");
	miCharFont = miOptions->Add(L"&Font For 'As String...' Display");
	miHistOpts = miOptions->Add(L"Histor&y Options...");
	miHelp = mnuMain->Add(L"&Help");
	miAbout = miHelp->Add(L"&About");
	miGenHelp = miHelp->Add(L"&General Help");
	miGenHelp->SetShortcut(L"F1");
	mnuMain->SetParent(this);

	pmCopy = new nlib::PopupMenu();
	miCopyDec = pmCopy->Add(L"Copy &Decimal");
	miCopyHex = pmCopy->Add(L"Copy He&xadecimal");
	miCopyOct = pmCopy->Add(L"Copy &Octal");
	miCopyBin = pmCopy->Add(L"Copy &Binary");
	miCopySep = pmCopy->Add(L"-");
	miCopyText = pmCopy->Add(L"Copy &Formula");
	pmCopy->SetParent(this);

	btnOpenHexOptions = new nlib::FlatButton();
	btnOpenHexOptions->SetBounds(nlib::Rect(14, 311, 242, 323));
	btnOpenHexOptions->SetText(L"-----------Hex. options------------------");
	btnOpenHexOptions->SetVisible(false);
	btnOpenHexOptions->GetFont().SetFamily(L"Tahoma");
	btnOpenHexOptions->GetFont().SetSize(10);
	btnOpenHexOptions->SetParentFont(false);
	btnOpenHexOptions->SetTabOrder(10);
	btnOpenHexOptions->SetParent(this);

	btnOpenDecOptions = new nlib::FlatButton();
	btnOpenDecOptions->SetBounds(nlib::Rect(14, 175, 242, 187));
	btnOpenDecOptions->SetText(L"-----------Decimal options--------------");
	btnOpenDecOptions->SetVisible(false);
	btnOpenDecOptions->GetFont().SetFamily(L"Tahoma");
	btnOpenDecOptions->GetFont().SetSize(10);
	btnOpenDecOptions->SetParentFont(false);
	btnOpenDecOptions->SetTabOrder(9);
	btnOpenDecOptions->SetParent(this);

	pToolbar = new nlib::Panel();
	pToolbar->SetBounds(nlib::Rect(0, 0, 528, 29));
	pToolbar->SetAlignment(nlib::alTop);
	pToolbar->SetTabOrder(1);
	pToolbar->SetInnerBorderStyle(nlib::pbsNone);
	pToolbar->SetParent(this);

	tbExit = new nlib::FlatButton();
	tbExit->SetBounds(nlib::Rect(0, 0, 23, 23));
	tbExit->GetFont().SetFamily(L"Tahoma");
	tbExit->GetFont().SetSize(10);
	tbExit->SetParentFont(false);
	tbExit->SetTabOrder(0);
	tbExit->SetParent(pToolbar);

	Bevel1 = new nlib::Bevel();
	Bevel1->SetBounds(nlib::Rect(26, 1, 28, 22));
	Bevel1->SetShape(nlib::bstLeftLine);
	Bevel1->SetParent(pToolbar);

	tbHistory = new nlib::FlatButton();
	tbHistory->SetBounds(nlib::Rect(31, 0, 54, 23));
	tbHistory->GetFont().SetFamily(L"Tahoma");
	tbHistory->GetFont().SetSize(10);
	tbHistory->SetParentFont(false);
	tbHistory->SetTabOrder(1);
	tbHistory->SetParent(pToolbar);

	tbCopy = new nlib::FlatButton();
	tbCopy->SetBounds(nlib::Rect(55, 0, 78, 23));
	tbCopy->GetFont().SetFamily(L"Tahoma");
	tbCopy->GetFont().SetSize(10);
	tbCopy->SetParentFont(false);
	tbCopy->SetTabOrder(2);
	tbCopy->SetParent(pToolbar);

	tbPaste = new nlib::FlatButton();
	tbPaste->SetBounds(nlib::Rect(79, 0, 102, 23));
	tbPaste->SetEnabled(false);
	tbPaste->GetFont().SetFamily(L"Tahoma");
	tbPaste->GetFont().SetSize(10);
	tbPaste->SetParentFont(false);
	tbPaste->SetTabOrder(3);
	tbPaste->SetParent(pToolbar);

	edtInfix = new nlib::Edit();
	edtInfix->SetBounds(nlib::Rect(8, 29, 521, 51));
	edtInfix->SetAnchors(nlib::caLeft | nlib::caTop | nlib::caRight | nlib::caBottom);
	edtInfix->GetFont().SetFamily(L"Tahoma");
	edtInfix->GetFont().SetSize(10);
	edtInfix->SetParentFont(false);
	edtInfix->SetTabOrder(0);
	edtInfix->SetParent(this);

	gbResults = new nlib::Groupbox();
	gbResults->SetBounds(nlib::Rect(16, 52, 521, 175));
	gbResults->SetText(L"Result");
	gbResults->SetPadding(nlib::Rect(0, 0, 0, 0));
	gbResults->GetFont().SetFamily(L"Tahoma");
	gbResults->GetFont().SetSize(10);
	gbResults->SetParentFont(false);
	gbResults->SetTabOrder(2);
	gbResults->SetParent(this);

	btnDecimal = new nlib::Button();
	btnDecimal->SetBounds(nlib::Rect(1, 16, 80, 39));
	btnDecimal->SetText(L"Deci&mal");
	btnDecimal->SetTabOrder(1);
	btnDecimal->SetTooltipText(L"Copy decimal number to clipboard");
	btnDecimal->SetParent(gbResults);

	btnHexadecimal = new nlib::Button();
	btnHexadecimal->SetTag(1);
	btnHexadecimal->SetBounds(nlib::Rect(1, 41, 80, 64));
	btnHexadecimal->SetText(L"&Hexadecimal");
	btnHexadecimal->SetTabOrder(2);
	btnHexadecimal->SetTooltipText(L"Copy hexadec. number to clipboard");
	btnHexadecimal->SetParent(gbResults);

	btnOctal = new nlib::Button();
	btnOctal->SetTag(2);
	btnOctal->SetBounds(nlib::Rect(2, 67, 81, 90));
	btnOctal->SetText(L"O&ctal");
	btnOctal->SetTabOrder(4);
	btnOctal->SetTooltipText(L"Copy octal number to clipboard");
	btnOctal->SetParent(gbResults);

	btnBinary = new nlib::Button();
	btnBinary->SetTag(3);
	btnBinary->SetBounds(nlib::Rect(2, 94, 81, 117));
	btnBinary->SetText(L"&Binary");
	btnBinary->SetTabOrder(6);
	btnBinary->SetTooltipText(L"Copy binary number to clipboard");
	btnBinary->SetParent(gbResults);

	pnlDec = new nlib::Panel();
	pnlDec->SetBounds(nlib::Rect(83, 15, 500, 40));
	pnlDec->GetFont().SetFamily(L"Arial");
	pnlDec->GetFont().SetSize(10);
	pnlDec->GetFont().SetCharacterSet(nlib::fcsAnsi);
	pnlDec->GetFont().SetOutputQuality(nlib::foqDraft);
	pnlDec->SetParentFont(false);
	pnlDec->SetTabOrder(0);
	pnlDec->SetShowText(false);
	pnlDec->SetInnerBorderStyle(nlib::pbsSunken);
	pnlDec->SetTextAlignment(nlib::taRight);
	pnlDec->SetParent(gbResults);

	pnlHex = new nlib::Panel();
	pnlHex->SetBounds(nlib::Rect(83, 41, 500, 66));
	pnlHex->GetFont().SetFamily(L"Arial");
	pnlHex->GetFont().SetSize(10);
	pnlHex->SetParentFont(false);
	pnlHex->SetTabOrder(3);
	pnlHex->SetInnerBorderStyle(nlib::pbsSunken);
	pnlHex->SetTextAlignment(nlib::taRight);
	pnlHex->SetParent(gbResults);

	pnlOct = new nlib::Panel();
	pnlOct->SetBounds(nlib::Rect(83, 67, 500, 92));
	pnlOct->GetFont().SetFamily(L"Arial");
	pnlOct->GetFont().SetSize(10);
	pnlOct->SetParentFont(false);
	pnlOct->SetTabOrder(5);
	pnlOct->SetInnerBorderStyle(nlib::pbsSunken);
	pnlOct->SetTextAlignment(nlib::taRight);
	pnlOct->SetParent(gbResults);

	pnlBin = new nlib::Panel();
	pnlBin->SetBounds(nlib::Rect(83, 93, 500, 118));
	pnlBin->GetFont().SetFamily(L"Arial");
	pnlBin->GetFont().SetSize(10);
	pnlBin->SetParentFont(false);
	pnlBin->SetTabOrder(7);
	pnlBin->SetInnerBorderStyle(nlib::pbsSunken);
	pnlBin->SetTextAlignment(nlib::taRight);
	pnlBin->SetParent(gbResults);

	pnlDecOpt = new nlib::Panel();
	pnlDecOpt->SetBounds(nlib::Rect(8, 191, 513, 301));
	pnlDecOpt->SetTabOrder(3);
	pnlDecOpt->SetInnerBorderStyle(nlib::pbsNone);
	pnlDecOpt->SetParent(this);

	gbDecOptions = new nlib::Groupbox();
	gbDecOptions->SetBounds(nlib::Rect(11, 1, 230, 105));
	gbDecOptions->SetText(L"Decimal options");
	gbDecOptions->SetPadding(nlib::Rect(0, 0, 0, 0));
	gbDecOptions->GetFont().SetFamily(L"Tahoma");
	gbDecOptions->GetFont().SetSize(10);
	gbDecOptions->SetParentFont(false);
	gbDecOptions->SetTabOrder(0);
	gbDecOptions->SetParent(pnlDecOpt);

	chkSep = new nlib::Checkbox();
	chkSep->SetBounds(nlib::Rect(8, 16, 165, 33));
	chkSep->SetText(L"Use t&housand separator:");
	chkSep->GetFont().SetFamily(L"Tahoma");
	chkSep->GetFont().SetSize(10);
	chkSep->SetParentFont(false);
	chkSep->SetTabOrder(0);
	chkSep->SetState(nlib::csChecked);
	chkSep->SetParent(gbDecOptions);

	cbThousandSep = new nlib::Combobox();
	cbThousandSep->SetBounds(nlib::Rect(168, 13, 215, 37));
	cbThousandSep->SetText(L"spc");
	cbThousandSep->GetFont().SetFamily(L"Tahoma");
	cbThousandSep->GetFont().SetSize(10);
	cbThousandSep->SetParentFont(false);
	cbThousandSep->SetTabOrder(1);
	cbThousandSep->SetType(nlib::ctDropdownList);
	cbThousandSep->Items().Add(L"spc");
	cbThousandSep->Items().Add(L",");
	cbThousandSep->Items().Add(L".");
	cbThousandSep->Items().Add(L";");
	cbThousandSep->SetItemIndex(0);
	cbThousandSep->SetParent(gbDecOptions);

	chkSci = new nlib::Checkbox();
	chkSci->SetBounds(nlib::Rect(8, 45, 141, 62));
	chkSci->SetText(L"&Scientific format");
	chkSci->GetFont().SetFamily(L"Tahoma");
	chkSci->GetFont().SetSize(10);
	chkSci->SetParentFont(false);
	chkSci->SetTabOrder(2);
	chkSci->SetParent(gbDecOptions);

	chkEng = new nlib::Checkbox();
	chkEng->SetBounds(nlib::Rect(8, 62, 149, 79));
	chkEng->SetText(L"Engeneering f&ormat");
	chkEng->GetFont().SetFamily(L"Tahoma");
	chkEng->GetFont().SetSize(10);
	chkEng->SetParentFont(false);
	chkEng->SetTabOrder(3);
	chkEng->SetParent(gbDecOptions);

	chkDecDigits = new nlib::Checkbox();
	chkDecDigits->SetBounds(nlib::Rect(8, 80, 149, 97));
	chkDecDigits->SetText(L"&Decimal digits:");
	chkDecDigits->GetFont().SetFamily(L"Tahoma");
	chkDecDigits->GetFont().SetSize(10);
	chkDecDigits->SetParentFont(false);
	chkDecDigits->SetTabOrder(4);
	chkDecDigits->SetParent(gbDecOptions);

	spnDecDigits = new nlib::Edit();
	spnDecDigits->SetBounds(nlib::Rect(141, 77, 178, 98));
	spnDecDigits->SetText(L"0");
	spnDecDigits->GetFont().SetFamily(L"Tahoma");
	spnDecDigits->GetFont().SetSize(10);
	spnDecDigits->SetParentFont(false);
	spnDecDigits->SetTabOrder(5);
	spnDecDigits->SetParent(gbDecOptions);

	UpDown1 = new nlib::UpDown();
	UpDown1->SetBounds(nlib::Rect(177, 77, 194, 98));
	UpDown1->SetMaxValue(20);
	UpDown1->SetParent(gbDecOptions);

	chkDecDelim = new nlib::Checkbox();
	chkDecDelim->SetBounds(nlib::Rect(8, 31, 160, 47));
	chkDecDelim->SetText(L"Use decimal separator");
	chkDecDelim->SetTabOrder(6);
	chkDecDelim->SetParent(gbDecOptions);

	gbAngleUnit = new nlib::Groupbox();
	gbAngleUnit->SetBounds(nlib::Rect(236, 7, 492, 53));
	gbAngleUnit->SetText(L"Angles in");
	gbAngleUnit->SetPadding(nlib::Rect(0, 0, 0, 0));
	gbAngleUnit->GetFont().SetFamily(L"Tahoma");
	gbAngleUnit->GetFont().SetSize(10);
	gbAngleUnit->SetParentFont(false);
	gbAngleUnit->SetTabOrder(1);
	gbAngleUnit->SetParent(pnlDecOpt);

	rdDeg = new nlib::Radiobox();
	rdDeg->SetBounds(nlib::Rect(11, 19, 59, 35));
	rdDeg->SetText(L"De&g");
	rdDeg->GetFont().SetFamily(L"Tahoma");
	rdDeg->GetFont().SetSize(10);
	rdDeg->SetParentFont(false);
	rdDeg->SetTabOrder(0);
	rdDeg->SetTooltipText(L"Degrees");
	rdDeg->SetChecked(true);
	rdDeg->SetParent(gbAngleUnit);

	rdGrad = new nlib::Radiobox();
	rdGrad->SetTag(2);
	rdGrad->SetBounds(nlib::Rect(121, 19, 177, 35));
	rdGrad->SetText(L"&Grad");
	rdGrad->GetFont().SetFamily(L"Tahoma");
	rdGrad->GetFont().SetSize(10);
	rdGrad->SetParentFont(false);
	rdGrad->SetTabOrder(2);
	rdGrad->SetTooltipText(L"360º = 400 grad");
	rdGrad->SetParent(gbAngleUnit);

	rdRad = new nlib::Radiobox();
	rdRad->SetTag(1);
	rdRad->SetBounds(nlib::Rect(64, 19, 119, 35));
	rdRad->SetText(L"&Rad");
	rdRad->GetFont().SetFamily(L"Tahoma");
	rdRad->GetFont().SetSize(10);
	rdRad->SetParentFont(false);
	rdRad->SetTabOrder(1);
	rdRad->SetTooltipText(L"Radians");
	rdRad->SetParent(gbAngleUnit);

	rdTurn = new nlib::Radiobox();
	rdTurn->SetTag(3);
	rdTurn->SetBounds(nlib::Rect(186, 19, 250, 37));
	rdTurn->SetText(L"&Turns");
	rdTurn->SetTabOrder(3);
	rdTurn->SetTooltipText(L"360º = 1 turn");
	rdTurn->SetParent(gbAngleUnit);

	Radiobox2 = new nlib::Radiobox();
	Radiobox2->SetBounds(nlib::Rect(100, 22, 196, 22));
	Radiobox2->SetText(L"Radiobox2");
	Radiobox2->SetTabOrder(4);
	Radiobox2->SetParent(gbAngleUnit);

	gbDisplayFormat = new nlib::Groupbox();
	gbDisplayFormat->SetBounds(nlib::Rect(236, 47, 492, 93));
	gbDisplayFormat->SetText(L"Display");
	gbDisplayFormat->SetPadding(nlib::Rect(0, 0, 0, 0));
	gbDisplayFormat->GetFont().SetFamily(L"Tahoma");
	gbDisplayFormat->GetFont().SetSize(10);
	gbDisplayFormat->SetParentFont(false);
	gbDisplayFormat->SetTabOrder(2);
	gbDisplayFormat->SetParent(pnlDecOpt);

	rdNormal = new nlib::Radiobox();
	rdNormal->SetBounds(nlib::Rect(11, 19, 91, 35));
	rdNormal->SetText(L"Norm&al");
	rdNormal->GetFont().SetFamily(L"Tahoma");
	rdNormal->GetFont().SetSize(10);
	rdNormal->SetParentFont(false);
	rdNormal->SetTabOrder(0);
	rdNormal->SetTooltipText(L"Exponent display with 10's power");
	rdNormal->SetChecked(true);
	rdNormal->SetParent(gbDisplayFormat);

	rdHtml = new nlib::Radiobox();
	rdHtml->SetTag(1);
	rdHtml->SetBounds(nlib::Rect(77, 20, 141, 36));
	rdHtml->SetText(L"&HTML");
	rdHtml->GetFont().SetFamily(L"Tahoma");
	rdHtml->GetFont().SetSize(10);
	rdHtml->SetParentFont(false);
	rdHtml->SetTabOrder(1);
	rdHtml->SetTooltipText(L"Exponent display with <sup>x</sup>");
	rdHtml->SetParent(gbDisplayFormat);

	rdTex = new nlib::Radiobox();
	rdTex->SetTag(2);
	rdTex->SetBounds(nlib::Rect(142, 20, 190, 36));
	rdTex->SetText(L"&TeX");
	rdTex->GetFont().SetFamily(L"Tahoma");
	rdTex->GetFont().SetSize(10);
	rdTex->SetParentFont(false);
	rdTex->SetTabOrder(2);
	rdTex->SetTooltipText(L"Exponent display with {10^x}");
	rdTex->SetParent(gbDisplayFormat);

	rdNone = new nlib::Radiobox();
	rdNone->SetTag(3);
	rdNone->SetBounds(nlib::Rect(198, 20, 238, 36));
	rdNone->SetText(L"E");
	rdNone->SetTabOrder(3);
	rdNone->SetTooltipText(L"Exponent display as 'Ex'");
	rdNone->SetParent(gbDisplayFormat);

	pnlHexOpt = new nlib::Panel();
	pnlHexOpt->SetBounds(nlib::Rect(8, 325, 515, 407));
	pnlHexOpt->SetTabOrder(4);
	pnlHexOpt->SetInnerBorderStyle(nlib::pbsNone);
	pnlHexOpt->SetParent(this);

	gbHexOptions = new nlib::Groupbox();
	gbHexOptions->SetBounds(nlib::Rect(8, 1, 493, 75));
	gbHexOptions->SetText(L"Hexadecimal Options");
	gbHexOptions->SetPadding(nlib::Rect(0, 0, 0, 0));
	gbHexOptions->GetFont().SetFamily(L"Tahoma");
	gbHexOptions->GetFont().SetSize(10);
	gbHexOptions->SetParentFont(false);
	gbHexOptions->SetTabOrder(0);
	gbHexOptions->SetParent(pnlHexOpt);

	chkMinus = new nlib::Checkbox();
	chkMinus->SetBounds(nlib::Rect(8, 18, 94, 35));
	chkMinus->SetText(L"M&inus sign");
	chkMinus->GetFont().SetFamily(L"Tahoma");
	chkMinus->GetFont().SetSize(10);
	chkMinus->SetParentFont(false);
	chkMinus->SetTabOrder(0);
	chkMinus->SetTooltipText(L"Absolute value of negative numbers are shown with a minus sign");
	chkMinus->SetParent(gbHexOptions);

	chkLittleEndian = new nlib::Checkbox();
	chkLittleEndian->SetTag(6);
	chkLittleEndian->SetBounds(nlib::Rect(360, 20, 446, 37));
	chkLittleEndian->SetText(L"&Little endian");
	chkLittleEndian->GetFont().SetFamily(L"Tahoma");
	chkLittleEndian->GetFont().SetSize(10);
	chkLittleEndian->SetParentFont(false);
	chkLittleEndian->SetTabOrder(1);
	chkLittleEndian->SetTooltipText(L"Left to right order of bytes from least significant to most significant (Intel ordering)");
	chkLittleEndian->SetParent(gbHexOptions);

	chkBytes = new nlib::Checkbox();
	chkBytes->SetTag(1);
	chkBytes->SetBounds(nlib::Rect(116, 18, 202, 35));
	chkBytes->SetText(L"As B&ytes");
	chkBytes->GetFont().SetFamily(L"Tahoma");
	chkBytes->GetFont().SetSize(10);
	chkBytes->SetParentFont(false);
	chkBytes->SetTabOrder(2);
	chkBytes->SetParent(gbHexOptions);

	chkWords = new nlib::Checkbox();
	chkWords->SetTag(2);
	chkWords->SetBounds(nlib::Rect(116, 35, 202, 52));
	chkWords->SetText(L"As &Words");
	chkWords->GetFont().SetFamily(L"Tahoma");
	chkWords->GetFont().SetSize(10);
	chkWords->SetParentFont(false);
	chkWords->SetTabOrder(3);
	chkWords->SetParent(gbHexOptions);

	chkDWords = new nlib::Checkbox();
	chkDWords->SetTag(3);
	chkDWords->SetBounds(nlib::Rect(116, 52, 202, 69));
	chkDWords->SetText(L"As DWo&rds");
	chkDWords->GetFont().SetFamily(L"Tahoma");
	chkDWords->GetFont().SetSize(10);
	chkDWords->SetParentFont(false);
	chkDWords->SetTabOrder(4);
	chkDWords->SetParent(gbHexOptions);

	chkIEEESingle = new nlib::Checkbox();
	chkIEEESingle->SetTag(4);
	chkIEEESingle->SetBounds(nlib::Rect(203, 18, 321, 35));
	chkIEEESingle->SetText(L"As IEE &754 single");
	chkIEEESingle->GetFont().SetFamily(L"Tahoma");
	chkIEEESingle->GetFont().SetSize(10);
	chkIEEESingle->SetParentFont(false);
	chkIEEESingle->SetTabOrder(5);
	chkIEEESingle->SetTooltipText(L"Single precision floating point format");
	chkIEEESingle->SetParent(gbHexOptions);

	chkIEEEDouble = new nlib::Checkbox();
	chkIEEEDouble->SetTag(5);
	chkIEEEDouble->SetBounds(nlib::Rect(203, 35, 321, 52));
	chkIEEEDouble->SetText(L"As IEE 7&54 double");
	chkIEEEDouble->GetFont().SetFamily(L"Tahoma");
	chkIEEEDouble->GetFont().SetSize(10);
	chkIEEEDouble->SetParentFont(false);
	chkIEEEDouble->SetTabOrder(6);
	chkIEEEDouble->SetTooltipText(L"Double precision floating point format");
	chkIEEEDouble->SetParent(gbHexOptions);

	chkHexPrefix = new nlib::Checkbox();
	chkHexPrefix->SetBounds(nlib::Rect(8, 52, 104, 68));
	chkHexPrefix->SetText(L"0x &prefix");
	chkHexPrefix->SetTabOrder(7);
	chkHexPrefix->SetParent(gbHexOptions);

	Label1 = new nlib::Label();
	Label1->SetBounds(nlib::Rect(256, 177, 313, 193));
	Label1->SetText(L"As String:");
	Label1->GetFont().SetFamily(L"Tahoma");
	Label1->GetFont().SetSize(10);
	Label1->SetParentFont(false);
	Label1->SetParent(this);

	edtChars = new nlib::Edit();
	edtChars->SetBounds(nlib::Rect(317, 176, 438, 197));
	edtChars->GetFont().SetFamily(L"Tahoma");
	edtChars->GetFont().SetSize(10);
	edtChars->SetParentFont(false);
	edtChars->SetTabOrder(5);
	edtChars->SetReadOnly(true);
	edtChars->SetParent(this);

	btnFont = new nlib::FlatButton();
	btnFont->SetBounds(nlib::Rect(440, 175, 508, 198));
	btnFont->SetText(L"&Font...");
	btnFont->GetFont().SetFamily(L"Tahoma");
	btnFont->GetFont().SetSize(10);
	btnFont->SetParentFont(false);
	btnFont->SetTabOrder(6);
	btnFont->SetAcceptInput(true);
	btnFont->SetFlat(false);
	btnFont->SetParent(this);

	btnCloseDecOptions = new nlib::FlatButton();
	btnCloseDecOptions->SetBounds(nlib::Rect(14, 175, 242, 187));
	btnCloseDecOptions->SetText(L"-------------------------------------------");
	btnCloseDecOptions->GetFont().SetFamily(L"Tahoma");
	btnCloseDecOptions->GetFont().SetSize(10);
	btnCloseDecOptions->SetParentFont(false);
	btnCloseDecOptions->SetTabOrder(7);
	btnCloseDecOptions->SetParent(this);

	btnCloseHexOptions = new nlib::FlatButton();
	btnCloseHexOptions->SetBounds(nlib::Rect(14, 311, 242, 323));
	btnCloseHexOptions->SetText(L"-------------------------------------------");
	btnCloseHexOptions->GetFont().SetFamily(L"Tahoma");
	btnCloseHexOptions->GetFont().SetSize(10);
	btnCloseHexOptions->SetParentFont(false);
	btnCloseHexOptions->SetTabOrder(8);
	btnCloseHexOptions->SetParent(this);

	btnClearInfix = new nlib::FlatButton();
	btnClearInfix->SetBounds(nlib::Rect(502, 29, 521, 50));
	btnClearInfix->SetText(L"x");
	btnClearInfix->SetBorderStyle(nlib::bsSingle);
	btnClearInfix->SetAnchors(nlib::caTop | nlib::caRight);
	btnClearInfix->SetTabOrder(11);
	btnClearInfix->SetMargin(0);
	btnClearInfix->SetParent(this);

	SetActiveControl(edtInfix);
	SetMenu(mnuMain);
	btnOpenHexOptions->Image()->SetBitmap(new nlib::Bitmap(NULL, MAKEINTRESOURCE(28672)));
	btnOpenDecOptions->Image()->SetBitmap(new nlib::Bitmap(NULL, MAKEINTRESOURCE(28673)));
	tbExit->Image()->SetBitmap(new nlib::Bitmap(NULL, MAKEINTRESOURCE(28674)));
	tbHistory->Image()->SetBitmap(new nlib::Bitmap(NULL, MAKEINTRESOURCE(28675)));
	tbCopy->Image()->SetBitmap(new nlib::Bitmap(NULL, MAKEINTRESOURCE(28676)));
	tbPaste->Image()->SetBitmap(new nlib::Bitmap(NULL, MAKEINTRESOURCE(28677)));
	pnlDec->SetPopupMenu(pmCopy);
	pnlHex->SetPopupMenu(pmCopy);
	pnlOct->SetPopupMenu(pmCopy);
	pnlBin->SetPopupMenu(pmCopy);
	UpDown1->SetAttachedEditor(spnDecDigits);
	btnFont->Image()->SetBitmap(new nlib::Bitmap(NULL, MAKEINTRESOURCE(28678)));
	btnFont->Image()->SetStateCount(2);
	btnCloseDecOptions->Image()->SetBitmap(new nlib::Bitmap(NULL, MAKEINTRESOURCE(28679)));
	btnCloseHexOptions->Image()->SetBitmap(new nlib::Bitmap(NULL, MAKEINTRESOURCE(28680)));

	OnStartSizeMove = CreateEvent(this, &TfrmMain::StartMove);
	OnMove = CreateEvent(this, &TfrmMain::FormMove);
	OnClose = CreateEvent(this, &TfrmMain::FormClose);
	miExit->OnClick = CreateEvent(this, &TfrmMain::miExitClick);
	miCopy->OnClick = CreateEvent(this, &TfrmMain::miCopyClick);
	miPaste->OnClick = CreateEvent(this, &TfrmMain::miPasteClick);
	miAppend->OnClick = CreateEvent(this, &TfrmMain::miAppendClick);
	miCopyDecimal->OnClick = CreateEvent(this, &TfrmMain::miCopyDecClick);
	miCopyHexadecimal->OnClick = CreateEvent(this, &TfrmMain::miCopyHexClick);
	miCopyOctal->OnClick = CreateEvent(this, &TfrmMain::miCopyOctClick);
	miCopyBinary->OnClick = CreateEvent(this, &TfrmMain::miCopyBinClick);
	miClearHist->OnClick = CreateEvent(this, &TfrmMain::miClearHistClick);
	miEditVars->OnClick = CreateEvent(this, &TfrmMain::miEditVarsClick);
	miEditFuncs->OnClick = CreateEvent(this, &TfrmMain::miEditFuncsClick);
	miShowHist->OnClick = CreateEvent(this, &TfrmMain::miShowHistClick);
	miShowDecOpts->OnClick = CreateEvent(this, &TfrmMain::miShowDecOptsClick);
	miShowHexOpts->OnClick = CreateEvent(this, &TfrmMain::miShowHexOptsClick);
	miCharFont->OnClick = CreateEvent(this, &TfrmMain::miCharFontClick);
	miHistOpts->OnClick = CreateEvent(this, &TfrmMain::miHistOptsClick);
	miAbout->OnClick = CreateEvent(this, &TfrmMain::miAboutClick);
	miGenHelp->OnClick = CreateEvent(this, &TfrmMain::miGenHelpClick);
	miCopyDec->OnClick = CreateEvent(this, &TfrmMain::miCopyDecClick);
	miCopyHex->OnClick = CreateEvent(this, &TfrmMain::miCopyHexClick);
	miCopyOct->OnClick = CreateEvent(this, &TfrmMain::miCopyOctClick);
	miCopyBin->OnClick = CreateEvent(this, &TfrmMain::miCopyBinClick);
	miCopyText->OnClick = CreateEvent(this, &TfrmMain::miCopyClick);
	btnOpenHexOptions->OnClick = CreateEvent(this, &TfrmMain::btnOpenHexOptionsClick);
	btnOpenDecOptions->OnClick = CreateEvent(this, &TfrmMain::btnOpenDecOptionsClick);
	tbExit->OnClick = CreateEvent(this, &TfrmMain::tbExitClick);
	tbHistory->OnClick = CreateEvent(this, &TfrmMain::tbHistoryClick);
	tbCopy->OnClick = CreateEvent(this, &TfrmMain::tbCopyClick);
	tbPaste->OnClick = CreateEvent(this, &TfrmMain::tbPasteClick);
	edtInfix->OnKeyDown = CreateEvent(this, &TfrmMain::edtInfixKeyDown);
	edtInfix->OnTextChanged = CreateEvent(this, &TfrmMain::edtInfixTextChanged);
	btnDecimal->OnClick = CreateEvent(this, &TfrmMain::btnCopyFormatClick);
	btnHexadecimal->OnClick = CreateEvent(this, &TfrmMain::btnCopyFormatClick);
	btnOctal->OnClick = CreateEvent(this, &TfrmMain::btnCopyFormatClick);
	btnBinary->OnClick = CreateEvent(this, &TfrmMain::btnCopyFormatClick);
	pnlDec->OnPaint = CreateEvent(this, &TfrmMain::pnlDecPaint);
	chkSep->OnClick = CreateEvent(this, &TfrmMain::chkSepClick);
	cbThousandSep->OnChanged = CreateEvent(this, &TfrmMain::cbThousandSepChanged);
	chkSci->OnClick = CreateEvent(this, &TfrmMain::chkSciClick);
	chkEng->OnClick = CreateEvent(this, &TfrmMain::chkSciClick);
	chkDecDigits->OnClick = CreateEvent(this, &TfrmMain::chkDecDigitsClick);
	spnDecDigits->OnTextChanged = CreateEvent(this, &TfrmMain::spnDecDigitsTextChanged);
	rdDeg->OnClick = CreateEvent(this, &TfrmMain::rdDegClick);
	rdGrad->OnClick = CreateEvent(this, &TfrmMain::rdDegClick);
	rdRad->OnClick = CreateEvent(this, &TfrmMain::rdDegClick);
	rdTurn->OnClick = CreateEvent(this, &TfrmMain::rdDegClick);
	rdNormal->OnClick = CreateEvent(this, &TfrmMain::rdNormalClick);
	rdHtml->OnClick = CreateEvent(this, &TfrmMain::rdNormalClick);
	rdTex->OnClick = CreateEvent(this, &TfrmMain::rdNormalClick);
	rdNone->OnClick = CreateEvent(this, &TfrmMain::rdNormalClick);
	chkMinus->OnClick = CreateEvent(this, &TfrmMain::chkMinusClick);
	chkLittleEndian->OnClick = CreateEvent(this, &TfrmMain::chkLittleEndianClick);
	chkBytes->OnClick = CreateEvent(this, &TfrmMain::chkAsBytesClick);
	chkWords->OnClick = CreateEvent(this, &TfrmMain::chkAsWordsClick);
	chkDWords->OnClick = CreateEvent(this, &TfrmMain::chkAsDWordsClick);
	chkIEEESingle->OnClick = CreateEvent(this, &TfrmMain::chkIEEESingleClick);
	chkIEEEDouble->OnClick = CreateEvent(this, &TfrmMain::chkIEEEDoubleClick);
	btnFont->OnClick = CreateEvent(this, &TfrmMain::btnFontClick);
	btnCloseDecOptions->OnClick = CreateEvent(this, &TfrmMain::btnCloseDecOptionsClick);
	btnCloseHexOptions->OnClick = CreateEvent(this, &TfrmMain::btnCloseHexOptionsClick);
}

TfrmMain::TfrmMain()
{
	InitializeFormAndControls(); /* Control initializations. Do not remove. */
}

TfrmMain::~TfrmMain()
{
	/* Don't 'delete' the form. Call Destroy() instead which has access to the protected destructor. */
}

void TfrmMain::Destroy()
{
	/* Controls are valid here, but not in the destructor. */
	/* ... Your code here ... */

	Form::Destroy();
}

void TfrmMain::miExitClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::miCopyClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::miPasteClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::miAppendClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::miCopyDecClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::miCopyHexClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::miCopyOctClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::miCopyBinClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::miEditVarsClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::miEditFuncsClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::miShowHistClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::miClearHistClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::miShowDecOptsClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::miShowHexOptsClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::miCharFontClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::miHistOptsClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::miAboutClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::miGenHelpClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::btnOpenHexOptionsClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::btnOpenDecOptionsClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::btnCloseHexOptionsClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::btnCloseDecOptionsClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::btnFontClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::chkDoubleClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::chkSingleClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::chkAsDWordsClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::chkAsWordsClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::chkAsBytesClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::chkLittleEndianClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::chkMinusClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::rdDegClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::spnDecDigitsTextChanged(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::chkDecDigitsClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::chkSciClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::cbThousandSepChanged(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::chkSepClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::btnCopyFormatClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::edtInfixTextChanged(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::edtInfixKeyDown(void *sender, nlib::KeyParameters param)
{
	;
}

void TfrmMain::tbPasteClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::tbCopyClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::tbHistoryClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::tbExitClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::FormClose(void *sender, nlib::FormCloseParameters param)
{
	;
}

void TfrmMain::FormMove(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::StartMove(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::pnlDecPaint(void *sender, nlib::PaintParameters param)
{
	;
}

void TfrmMain::rdNormalClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::cbInfixTextChanged(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::cbInfixKeyPress(void *sender, nlib::KeyPressParameters param)
{
	;
}

void TfrmMain::chkIEEEDoubleClick(void *sender, nlib::EventParameters param)
{
	;
}

void TfrmMain::chkIEEESingleClick(void *sender, nlib::EventParameters param)
{
	;
}

