#include <set>
#include "stdafx_zoli.h"
#include "stdafx_lc.h"

using namespace nlib;
#undef max

#include "calculate.h"
#include "mainForm.h"
#include "variables.h"

TfrmVariables *frmVariables;

void TfrmVariables::InitializeFormAndControls() /* Control initialization function generated by the designer. Modifications will be lost. */
{
	/* Generated member initialization. Do not modify. */
	SetLeft(93);
	SetTop(327);
	SetText(L"FalconCalc Functions/Variables");
	GetFont().SetFamily(L"Tahoma");
	SetWantedKeyTypes(nlib::wkArrows | nlib::wkTab | nlib::wkEnter | nlib::wkEscape | nlib::wkOthers);
	SetClientRect(nlib::Rect(0, 0, 441, 569));

	tcVars = new nlib::TabControl();
	tcVars->SetBounds(nlib::Rect(0, 0, 352, 569));
	tcVars->SetText(L"tcVars");
	tcVars->SetAnchors(nlib::caLeft | nlib::caTop | nlib::caRight | nlib::caBottom);
	tcVars->SetTabOrder(0);
	nlib::Tab *temp_var0058244656 = tcVars->AddTab(L"&Functions");
	temp_var0058244656->SetTag(1);
	nlib::Tab *temp_var0058246008 = tcVars->AddTab(L"&Variables");
	tcVars->SetSelectedTab(1);
	tcVars->SetParent(this);

	sgUser = new nlib::StringGrid();
	sgUser->SetBounds(nlib::Rect(4, 23, 348, 319));
	sgUser->SetAlignment(nlib::alTop);
	sgUser->SetTabOrder(0);
	sgUser->SetColCount(3);
	sgUser->SetRowCount(5);
	sgUser->SetFixedColCount(0);
	sgUser->SetSelectionKind(nlib::gskNoSelect);
	sgUser->SetColumnsResizable(true);
	sgUser->SetColWidth(0, 87);
	sgUser->SetColWidth(1, 118);
	sgUser->SetColWidth(2, 129);
	sgUser->SetRowHeight(3, 21);
	sgUser->SetRowHeight(4, 23);
	sgUser->SetDefColWidth(0, 87);
	sgUser->SetDefColWidth(1, 118);
	sgUser->SetDefColWidth(2, 129);
	sgUser->SetSmoothHorzScroll(true);
	sgUser->SetAutoEdit(true);
	sgUser->SetTabEdited(true);
	sgUser->SetParent(tcVars);

	pBuiltin = new nlib::Panel();
	pBuiltin->SetBounds(nlib::Rect(4, 319, 348, 343));
	pBuiltin->SetText(L"Builtins");
	pBuiltin->SetAlignment(nlib::alTop);
	pBuiltin->SetParentBackground(true);
	pBuiltin->SetTabOrder(1);
	pBuiltin->SetInnerBorderStyle(nlib::pbsNone);
	pBuiltin->SetParent(tcVars);

	sgBuiltin = new nlib::StringGrid();
	sgBuiltin->SetBounds(nlib::Rect(4, 343, 348, 565));
	sgBuiltin->SetAlignment(nlib::alClient);
	sgBuiltin->SetTabOrder(2);
	sgBuiltin->SetColCount(3);
	sgBuiltin->SetRowCount(5);
	sgBuiltin->SetFixedColCount(0);
	sgBuiltin->SetFixedRowCount(0);
	sgBuiltin->SetSelectionKind(nlib::gskNoSelect);
	sgBuiltin->SetColumnsResizable(true);
	sgBuiltin->SetColWidth(0, 88);
	sgBuiltin->SetColWidth(1, 118);
	sgBuiltin->SetColWidth(2, 129);
	sgBuiltin->SetRowHeight(2, 25);
	sgBuiltin->SetRowHeight(4, 20);
	sgBuiltin->SetDefColWidth(0, 88);
	sgBuiltin->SetDefColWidth(1, 118);
	sgBuiltin->SetDefColWidth(2, 129);
	sgBuiltin->SetSmoothHorzScroll(true);
	sgBuiltin->SetParent(tcVars);

	btnDelVar = new nlib::FlatButton();
	btnDelVar->SetBounds(nlib::Rect(357, 48, 380, 70));
	btnDelVar->SetAnchors(nlib::caTop | nlib::caRight);
	btnDelVar->SetTabOrder(1);
	btnDelVar->SetImagePosition(nlib::bipCenter);
	btnDelVar->SetFlat(false);
	btnDelVar->SetParent(this);

	btnClear = new nlib::FlatButton();
	btnClear->SetBounds(nlib::Rect(357, 76, 380, 98));
	btnClear->SetAnchors(nlib::caTop | nlib::caRight);
	btnClear->SetTabOrder(2);
	btnClear->SetImagePosition(nlib::bipCenter);
	btnClear->SetFlat(false);
	btnClear->SetParent(this);

	btnCancel = new nlib::Button();
	btnCancel->SetBounds(nlib::Rect(358, 497, 433, 520));
	btnCancel->SetText(L"&Cancel");
	btnCancel->SetAnchors(nlib::caRight | nlib::caBottom);
	btnCancel->SetTabOrder(3);
	btnCancel->SetParent(this);

	btnSave = new nlib::Button();
	btnSave->SetBounds(nlib::Rect(358, 524, 433, 547));
	btnSave->SetText(L"&Save");
	btnSave->SetAnchors(nlib::caRight | nlib::caBottom);
	btnSave->SetTabOrder(4);
	btnSave->SetParent(this);

	btnDelVar->Image()->SetBitmap(new nlib::Bitmap(NULL, MAKEINTRESOURCE(28683)));
	btnDelVar->Image()->SetStateCount(2);
	btnClear->Image()->SetBitmap(new nlib::Bitmap(NULL, MAKEINTRESOURCE(28684)));

	OnClose = CreateEvent(this, &TfrmVariables::FormClose);
	tcVars->OnTabChange = CreateEvent(this, &TfrmVariables::tcVarsTabChange);
	sgUser->OnColumnSizing = CreateEvent(this, &TfrmVariables::sgUserColumnSizing);
	sgUser->OnEditorKeyDown = CreateEvent(this, &TfrmVariables::sgUserEditorKeyDown);
	sgUser->OnEditorKeyPress = CreateEvent(this, &TfrmVariables::sgUserKeyPress);
	pBuiltin->OnMouseMove = CreateEvent(this, &TfrmVariables::BuiltinMouseMove);
	pBuiltin->OnMouseDown = CreateEvent(this, &TfrmVariables::BuiltinMouseDown);
	pBuiltin->OnMouseUp = CreateEvent(this, &TfrmVariables::BuiltinMouseUp);
	sgBuiltin->OnColumnSizing = CreateEvent(this, &TfrmVariables::sgBuiltinColumnSizing);
	btnDelVar->OnClick = CreateEvent(this, &TfrmVariables::btnDelVarClick);
	btnClear->OnClick = CreateEvent(this, &TfrmVariables::btnClearClick);
	btnCancel->OnClick = CreateEvent(this, &TfrmVariables::btnCancelClick);
	btnSave->OnClick = CreateEvent(this, &TfrmVariables::btnSaveClick);
}

void TfrmVariables::Destroy()
{
	/* Controls are valid here, but not in the destructor. */
	/* ... Your code here ... */

	Form::Destroy();
}

TfrmVariables::TfrmVariables()
{
	InitializeFormAndControls();

	_changed = false;
	_underResize = false;
}

TfrmVariables::~TfrmVariables()
{
	/* Don't 'delete' the form. Call Destroy() instead which has access to the protected destructor. */
}

void TfrmVariables::Setup(const FalconCalc::VARFUNC_INFO &vfInfo)
{
    _vf = vfInfo;
//	tcVarsTabChange(tcVars, TabChangeParameters(tcVars->SelectedTab()));
}


void TfrmVariables::BuiltinMouseDown(void *sender, nlib::MouseButtonParameters param)
{
	_underResize = true;
	_gridH = param.y;

}

void TfrmVariables::BuiltinMouseMove(void *sender, nlib::MouseMoveParameters param)
{
	if(!_underResize)
		return;
	int    rh = sgUser->DefaultRowHeight(),
		   h1 = sgUser->Height(),
		   h2 = sgBuiltin->Height(),
		   dh = param.y - _gridH;
	if(h1+dh > 2*rh && h2-dh > 2 *rh)
	{
		sgUser->SetHeight(h1+dh);
		_gridH += dh;
	}

}

void TfrmVariables::BuiltinMouseUp(void *sender, nlib::MouseButtonParameters param)
{
	_underResize = false;
}


/*============================================================================
 * TASK: get data from previous (!) TAB of tcVars
 *---------------------------------------------------------------------------*/
void TfrmVariables::_CollectInto(SmartString &us, size_t &cnt)
{
    if(!_changed)    // 'changed' must be modified in caller when necessary
        return;
    int n = 0; // count of user variables/functions
	us.clear();
    for(int i = 1; i < sgUser->RowCount(); ++i)
    {
        if(sgUser->String(0,i) != L"" && sgUser->String(1,i) != L"")
        {
            us = us + SmartString(sgUser->String(0,i) + L"=" + sgUser->String(1,i)+ wstring(1, comment_delimiter.Unicode()) + sgUser->String(2, i)+ L"\n");
            ++n;
        }
    }
    cnt = n;
}

void TfrmVariables::tcVarsTabChange(void *sender, nlib::TabChangeParameters param)
{
    size_t cntUser, cntBuiltin;
    SmartString *psUser, *psBuiltin;
    switch( tcVars->SelectedTab() )
    {
       case 0: _CollectInto(_vf.sUserVars, _vf.uUserVarCnt); break;
       case 1: _CollectInto(_vf.sUserFuncs,_vf.uUserFuncCnt); break;
    }
    _changed = false;

    switch( tcVars->SelectedTab() )
    {
	case 0:  
			sgUser->SetString(0,0,L"Name(args)");
			sgUser->SetString(1,0,L"Definition");
			sgUser->SetString(2,0,L"Comment");

             cntUser    = _vf.uUserFuncCnt;
             cntBuiltin = _vf.uBuiltinFuncCnt;
             psUser    = &_vf.sUserFuncs;
             psBuiltin = &_vf.sBuiltinFuncs;
             break;
    case 1:  
			sgUser->SetString(0,0,L"Variable");
			sgUser->SetString(1,0,L"Definition");
			sgUser->SetString(2,0,L"Comment");
			 
             cntUser    = _vf.uUserVarCnt;
             cntBuiltin = _vf.uBuiltinVarCnt;
             psUser    = &_vf.sUserVars;
             psBuiltin = &_vf.sBuiltinVars;
             break;
    }
    if((size_t)sgUser->RowCount() != cntUser + (cntUser ? 1 : 2))
        sgUser->SetRowCount(cntUser + (cntUser ? 1 : 2));
    if(cntUser == 0)
    {
		sgUser->SetString(0,1,L"");
		sgUser->SetString(1,1,L"");
		sgUser->SetString(2,1,L"");
    }
    if((size_t)sgBuiltin->RowCount() != cntBuiltin)
        sgBuiltin->SetRowCount(cntBuiltin);

    wstring s;
    size_t st = 0,seol, pos, posc;
    for(size_t i = 1; i <= cntUser; ++i)
    {
        seol = psUser->find_first_of('\n',st);
        s = ( (seol == string::npos ? psUser->mid(st) : psUser->mid(st, seol - st)) ).ToWideString();
        st = seol+1;
        pos = s.find_first_of('=');
        posc = s.find_first_of(comment_delimiter); // comment delimiter

		sgUser->SetString(0,i,s.substr(0,pos));
		sgUser->SetString(1,i,s.substr(pos+1, posc-pos-1));
		sgUser->SetString(2,i,s.substr(posc+1));
    }
    st = 0;
    for(size_t i = 0; i < cntBuiltin; ++i)
    {
        seol = psBuiltin->find_first_of('\n',st);
        s = ((seol == string::npos ? psBuiltin->mid(st) : psBuiltin->mid(st, seol - st))).ToWideString();
        st = seol+1;
        pos = s.find_first_of('=');
        posc = s.find_first_of(comment_delimiter,pos); // comment delimiter
		sgBuiltin->SetString(0,i,s.substr(0,pos));
		sgBuiltin->SetString(1,i,s.substr(pos+1, posc-pos-1));
		sgBuiltin->SetString(2,i,s.substr(posc+1));
    }
}

void TfrmVariables::btnCancelClick(void *sender, nlib::EventParameters param)
{
    Close();
}

void TfrmVariables::btnClearClick(void *sender, nlib::EventParameters param)
{
	sgUser->SetRowCount(2);
	sgUser->SetString(0,1,L"");
	sgUser->SetString(1,1,L"");
	sgUser->SetString(2,1,L"");
    _changed = true;
}

void TfrmVariables::btnDelVarClick(void *sender, nlib::EventParameters param)
{
	int n = sgUser->Selected().y;
    if(n > 0)
    {
/*
        for(int i = n+1; i < sgUser->RowCount(); ++i)
        {
			sgUser->SetString(0,i-1,sgUser->String(0,i));
			sgUser->SetString(1,i-1,sgUser->String(1,i));
			sgUser->SetString(2,i-1,sgUser->String(2,i));
        }
*/
        if(sgUser->RowCount() == 2) 
            btnClearClick(sender,param);
        else
			sgUser->DeleteRow(n);
//            sgUser->SetRowCount(sgUser->RowCount()-1); // = sgUser->RowCount - 1;
        _changed = true;
    }
}

void TfrmVariables::btnSaveClick(void *sender, nlib::EventParameters param)
{
    if(!_changed)
	{
        Close();
		return;
	}
    switch( tcVars->SelectedTab() )
    {
       case 0: _CollectInto(_vf.sUserFuncs,_vf.uUserFuncCnt); break;
       case 1: _CollectInto(_vf.sUserVars, _vf.uUserVarCnt); break;
    }

    frmMain->_pEngine()->AddUserVariablesAndFunctions(_vf.sUserFuncs, 2);
    frmMain->_pEngine()->AddUserVariablesAndFunctions(_vf.sUserVars,  1);
    frmMain->edtInfixTextChanged(sender,param); // to reflect changed values
    _changed = false;
    Close();
}

void TfrmVariables::sgBuiltinColumnSizing(void *sender, nlib::ColumnRowSizeParameters param)
{
//	if(under_sizing != 2)
//		return;
	sgUser->SetColWidth(param.index, param.size );
}

void TfrmVariables::sgUserColumnSizing(void *sender, nlib::ColumnRowSizeParameters param)
{
//	if(under_sizing != 1)
//		return;
	sgBuiltin->SetColWidth(param.index, param.size );
}

void TfrmVariables::FormClose(void *sender, nlib::FormCloseParameters param)
{
    param.action = caDeleteForm;
	frmVariables=NULL;
}

void TfrmVariables::sgUserKeyPress(void *sender, nlib::KeyPressParameters param)
{
	if(param.key != VK_TAB && param.key != VK_RIGHT && param.key != VK_LEFT && param.key != VK_UP && param.key != VK_DOWN)
		_changed = true;
}

void TfrmVariables::sgUserEditorKeyDown(void *sender, nlib::KeyParameters param)
{
	if(param.keycode != VK_TAB && param.keycode != VK_RIGHT && param.keycode != VK_LEFT && param.keycode != VK_UP && param.keycode != VK_DOWN)
		_changed = true;

	if(param.keycode == VK_TAB)
	{
//		int x = sgUser->Selected().x;
		if( (param.vkeys & vksShift) == 0 &&  sgUser->Selected().x >= 2)
		{
			int n = sgUser->Selected().y + 1;
			if(n >= sgUser->RowCount())
			{
				sgUser->SetRowCount(n+1);
				sgUser->SetString(0, n, L"");
				sgUser->SetString(1,n, L"");
				sgUser->SetString(2,n, L"");
			}
			sgUser->SetSelected(0,n);
		}
	}

}





