#undef set
#include <set>
#include "stdafx_zoli.h"
#include "stdafx_lc.h"
#include "general.h"
#include "common.h"
#include "wcommon.h"
#include "calculate.h"
#include "resource.h"
#include "variables.h"
#include "translations.h"
#include "string.h"
#include "VFDefDialog.h"

TVarFuncDefDialog *varFuncDefDialog;

void TVarFuncDefDialog::InitializeFormAndControls() /* Control initialization function generated by the designer. Modifications will be lost. */
{
	/* Generated member initialization. Do not modify. */
	SetLeft(795);
	SetTop(313);
	SetText(lt.GetTranslationFor(FCT_VNDIALOGTITLE));
	SetWantedKeyTypes(nlib::wkArrows | nlib::wkTab | nlib::wkEnter | nlib::wkEscape | nlib::wkOthers);
	SetMinimumWidth(423);
	SetMinimumHeight(229);
	SetMaximumWidth(423);
	SetMaximumHeight(229);
	SetClientRect(nlib::Rect(0, 0, 407, 190));

	lblDefinition = new nlib::Label();
	lblDefinition->SetBounds(nlib::Rect(81, 9, 146, 24));
	lblDefinition->SetText(L"...");
	lblDefinition->SetParent(this);

	lblName = new nlib::Label();
	lblName->SetBounds(nlib::Rect(17, 33, 52, 48));
	lblName->SetText(lt.GetTranslationFor(FCT_VNDNAME));
	lblName->SetParent(this);

	lblBodyValue = new nlib::Label();
	lblBodyValue->SetBounds(nlib::Rect(17, 62, 48, 77));
	lblBodyValue->SetText(lt.GetTranslationFor(FCT_VNDVALUE));
	lblBodyValue->SetParent(this);

	lblUnit = new nlib::Label();
	lblUnit->SetBounds(nlib::Rect(17, 91, 42, 106));
	lblUnit->SetText(lt.GetTranslationFor(FCT_VNDUNIT));
	lblUnit->SetParent(this);

	edtName = new nlib::Edit();
	edtName->SetBounds(nlib::Rect(80, 24, 384, 47));
	edtName->SetAnchors(nlib::caLeft | nlib::caTop | nlib::caRight);
	edtName->SetTabOrder(0);
	edtName->SetParent(this);

	edtBody = new nlib::Edit();
	edtBody->SetBounds(nlib::Rect(80, 56, 384, 79));
	edtBody->SetAnchors(nlib::caLeft | nlib::caTop | nlib::caRight);
	edtBody->SetTabOrder(1);
	edtBody->SetParent(this);

	edtUnit = new nlib::Edit();
	edtUnit->SetBounds(nlib::Rect(80, 88, 384, 111));
	edtUnit->SetAnchors(nlib::caLeft | nlib::caTop | nlib::caRight);
	edtUnit->SetTabOrder(2);
	edtUnit->SetParent(this);

	lblComment = new nlib::Label();
	lblComment->SetBounds(nlib::Rect(17, 121, 74, 136));
	lblComment->SetText(lt.GetTranslationFor(FCT_VNDCOMMENT));
	lblComment->SetParent(this);

	edtComment = new nlib::Edit();
	edtComment->SetBounds(nlib::Rect(80, 120, 384, 143));
	edtComment->SetAnchors(nlib::caLeft | nlib::caTop | nlib::caRight);
	edtComment->SetTabOrder(3);
	edtComment->SetParent(this);

	btnOk = new nlib::Button();
	btnOk->SetBounds(nlib::Rect(232, 154, 307, 177));
	btnOk->SetText(lt.GetTranslationFor(FCT_OK));
	btnOk->SetEnabled(false);
	btnOk->SetAnchors(nlib::caRight | nlib::caBottom);
	btnOk->SetTabOrder(4);
	btnOk->SetShowTooltip(false);
	btnOk->SetParentTooltip(false);
	btnOk->SetParent(this);

	btnCancel = new nlib::Button();
	btnCancel->SetBounds(nlib::Rect(320, 154, 395, 177));
	btnCancel->SetText(lt.GetTranslationFor(FCT_CANCEL));
	btnCancel->SetTabOrder(5);
	btnCancel->SetCancel(true);
	btnCancel->SetParent(this);


	edtName->OnTextChanged = CreateEvent(this, &TVarFuncDefDialog::edtName_textChanged);
	edtBody->OnTextChanged = CreateEvent(this, &TVarFuncDefDialog::edtBody_textChanged);
	btnOk->OnClick = CreateEvent(this, &TVarFuncDefDialog::btnOk_click);
	btnCancel->OnClick = CreateEvent(this, &TVarFuncDefDialog::btnCancel_click);
}

TVarFuncDefDialog::TVarFuncDefDialog(VarFuncData& vfd) : Form(), _vfd(vfd)
{
	InitializeFormAndControls(); /* Control initializations. Do not remove. */
	edtName->SetText(vfd.name);
	edtBody->SetText(vfd.body);
	edtUnit->SetText(vfd.unit);
	edtComment->SetText(vfd.comment);
	_ShowDefinition();
	_EnableDisableOkButton();
}

TVarFuncDefDialog::~TVarFuncDefDialog()
{
	/* Don't 'delete' the form. Call Destroy() instead which has access to the protected destructor. */
}

void TVarFuncDefDialog::_EnableDisableOkButton()
{
	// name and body must be non-empty
	btnOk->SetEnabled(!edtName->Text().empty() && !edtBody->Text().empty());
	if (_vfd.isFunction)
		lblDefinition->SetText(edtName->Text() + L'=' + edtBody->Text() + L":" + edtUnit->Text() + L':'+edtComment->Text());
}

void TVarFuncDefDialog::_Collect()
{
	_vfd.name = edtName->Text();
	_vfd.body = edtBody->Text();
	_vfd.unit = edtUnit->Text();
	_vfd.comment = edtComment->Text();
}

void TVarFuncDefDialog::_ShowDefinition()
{
	if (_vfd.isFunction)
	{
		if(edtName->Text().empty() || edtBody->Text().empty())
			lblDefinition->SetVisible(false);
		else
		{
			lblDefinition->SetVisible(true);
			lblDefinition->SetText(_vfd.name + L"=" + _vfd.body + L" - " + _vfd.comment);
		}
	}
	else
		lblDefinition->SetVisible(false);
}

void TVarFuncDefDialog::Destroy()
{
	/* Controls are valid here, but not in the destructor. */
	/* ... Your code here ... */

	Form::Destroy();
}

void TVarFuncDefDialog::edtName_textChanged(void *sender, nlib::EventParameters param)
{
	_EnableDisableOkButton();
}

void TVarFuncDefDialog::edtBody_textChanged(void *sender, nlib::EventParameters param)
{
	_EnableDisableOkButton();
}

void TVarFuncDefDialog::btnOk_click(void* sender, nlib::EventParameters param)
{
	_Collect();
	SetModalResult(nlib::mrOk);
}

void TVarFuncDefDialog::btnCancel_click(void* sender, nlib::EventParameters param)
{
	SetModalResult(nlib::mrCancel);

}
